CREATE TABLE CaseUpdate.CRMLostLeadResponses
(
	[ID] INT IDENTITY(1,1) NOT NULL,	
	[AuditID] INT NULL,
	[AuditItemID] INT NULL,
	[ParentAuditItemID] INT NULL,
	[PhysicalRowID] INT NULL,
	[Event ID] INT NULL,
	[Made enquiry about model] NVARCHAR(255) NULL,
	[Enquiry channel] NVARCHAR(255) NULL,
	[Other JLR model enquiry] NVARCHAR(255) NULL,
	[Other JLR Retailer visited - CA] NVARCHAR(255) NULL,
	[Other JLR Retailer visited - UK] NVARCHAR(255) NULL,
	[Other JLR Retailer visited - US] NVARCHAR(255) NULL,
	[Current Car Model] NVARCHAR(255) NULL,
	[Current Car Make] NVARCHAR(255) NULL,
	[Lost Leads NPS] INT NULL,
	[Did you get what you wanted] NVARCHAR(255) NULL,
	[Did you get what you wanted - comments] NVARCHAR(MAX) NULL,
	[Welcome] NVARCHAR(255) NULL,
	[Understanding wants/needs] NVARCHAR(255) NULL,
	[Explanation of features/benefits] NVARCHAR(255) NULL,
	[Test drive offered] NVARCHAR(255) NULL,
	[Follow up] NVARCHAR(255) NULL,
	[Additional comments about the experience] NVARCHAR(MAX) NULL,
	[Still considering purchasing] NVARCHAR(255) NULL,
	[Purchase date - month] NVARCHAR(255) NULL,
	[Purchase date - year] INT NULL,
	[Reason for postponing purchase] NVARCHAR(255) NULL,
	[Reason not buying a new car] NVARCHAR(255) NULL,
	[Reasons not buying JLR] NVARCHAR(255) NULL,
	[Circumstance change] NVARCHAR(255) NULL,
	[Overall vehicle reasons for non-purchase] NVARCHAR(1000) NULL,
	[The design] NVARCHAR(1000) NULL,
	[The quality] NVARCHAR(1000) NULL,
	[The performance and driving experience] NVARCHAR(1000) NULL,
	[The comfort and practicality] NVARCHAR(1000) NULL,
	[The options] NVARCHAR(1000) NULL,
	[Purchase Cost] NVARCHAR(1000) NULL,
	[Cost of Ownership] NVARCHAR(1000) NULL,
	[The quoted lead time] NVARCHAR(1000) NULL,
	[Reviews and recommendations] NVARCHAR(1000) NULL,
	[Vehicle non-purchase comments] NVARCHAR(MAX) NULL,
	[Overall Retailer reasons for non-purchase] NVARCHAR(1000) NULL,
	[The retailer showroom] NVARCHAR(1000) NULL,
	[The Retailer Staff] NVARCHAR(1000) NULL,
	[The Car and Test Drive Experience] NVARCHAR(1000) NULL,
	[Negotiation with retailer] NVARCHAR(1000) NULL,
	[Retailer non-purchase comments] NVARCHAR(MAX) NULL,
	[Main reason not to buy] NVARCHAR(1000) NULL,
	[Anonymous] NVARCHAR(255) NULL,
	[NPS - Why Do You Say That?] NVARCHAR(MAX) NULL,
	[Case ID] INT NULL
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
) ON [PRIMARY]
GO