CREATE TABLE [Warranty].[WarrantyEvents] (
    [WarrantyID]                         INT           IDENTITY (1, 1) NOT NULL,
    [SampleSupplierPartyID]              dbo.PartyID   NOT NULL,
    [ManufacturerID]                     dbo.PartyID   NOT NULL,
    [CICode]                             NCHAR (5)     NULL,
    [ClaimNumber]                        NCHAR (7)     NULL,
    [OverseasDealerCode]                 NCHAR (5)     NULL,
    [MarketOrig]                         SMALLINT      NULL,
    [CountryID]                          dbo.CountryID NULL,
    [VINPrefix]                          NVARCHAR(11) NULL,
    [ChassisNumber]                      NCHAR (6)     NOT NULL,
    [ComplaintCode]                      NCHAR (6)     NULL,
    [OdometerDistance]                   SMALLINT      NULL,
    [DistanceUnit]                       NCHAR (1)     NULL,
    [ClaimType]                          TINYINT       NULL,
    [DateOfRepairOrig]                   NVARCHAR (25) NULL,
    [DateOfRepair]                       DATETIME2     NULL,
    [DateOfSaleOrig]                     NCHAR (6)     NULL,
    [DateOfSale]                         DATETIME2     NULL,
    [AuditID]                            dbo.AuditID   NOT NULL,
    [VWTID]                              dbo.VWTID     NULL,
    [AuditItemID]                        dbo.AuditItemID    NULL,
    [PhysicalRow]                        INT           NOT NULL,
    [ServiceDealerCodeOriginatorPartyID] dbo.PartyID           NOT NULL,
    [MatchedODSVehicleID]                dbo.VehicleID           NOT NULL,
    [MatchedODSPersonID]                 dbo.PartyID           NOT NULL,
    [MatchedODSOrganisationID]           dbo.PartyID           NOT NULL,
    [DateTransferredToVWT]               DATETIME2      NULL,
    [ISOCountryCode]                     CHAR (3)      NULL,
    [RONumber]                           VARCHAR (6)   NULL,
    [ROSeqNumber]                        CHAR (1)      NULL,
    [CLAIMSTATUS]                        CHAR (1)      NULL,
    [WIAA02_CLAIM_TYPE_C]                CHAR (1)      NULL,
    [COVERAGECATEGORY]                   VARCHAR (100) NULL,
    [PROGRAMCODE]                        VARCHAR (100) NULL,
    [WIAA02_TOTAL_LABOR_A]               VARCHAR (100) NULL
);

