ALTER TABLE [CRM].[XMLOutputValues_Market]
    ADD CONSTRAINT [PK_CRM_XMLOutputValues_Market] PRIMARY KEY CLUSTERED (CountryID) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


 