ALTER TABLE [CRM].[XMLOutputValues_MarketQuestionnaire]
    ADD CONSTRAINT [PK_CRM_XMLOutputValues_MarketQuestionnaire] PRIMARY KEY CLUSTERED (CountryID, EventCategoryID, BrandID) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


 