ALTER TABLE [CRM].[ResponseMarketQuestionnaires]
    ADD CONSTRAINT [PK_CRM_ResponseMarketQuestionnaires] PRIMARY KEY CLUSTERED (CountryID, EventCategoryID) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


