ALTER TABLE [CRM].[OutputBatches]
    ADD CONSTRAINT [PK_OutputBatches] PRIMARY KEY CLUSTERED (Batch ASC, CaseID ASC, EventID ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


 