ALTER TABLE [CRM].[ResponseStatuses]
    ADD CONSTRAINT [PK_ResponseStatuses] PRIMARY KEY CLUSTERED (ResponseStatusID ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


 