ALTER TABLE [CRM].[ResponsesHeldBackDueToSizeLimits_ReleasedRecs]
    ADD CONSTRAINT [PK_ResponsesHeldBackDueToSizeLimits_ReleasedRecs] PRIMARY KEY CLUSTERED ([CaseID] ASC, EventID ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);


 