CREATE TABLE RollbackSample.CRCEvents
(
	[AuditID] [dbo].[AuditID] NOT NULL,

	[CRC_ID] [int] NOT NULL,

	[AuditItemID] [dbo].[AuditItemID] NOT NULL,
	[PhysicalRowID] [int] NOT NULL,

	[ODSEventID]		dbo.EventID NULL,
	[DateTransferredToVWT] [datetime2](7) NULL,

	CRCCode						dbo.Loadtext NULL,
	MarketCode					dbo.Loadtext NULL,
	BrandCode					dbo.Loadtext NULL,
	RunDateofExtract			dbo.Loadtext NULL,
	ExtractFromDate				dbo.Loadtext NULL,
	ExtractToDate				dbo.Loadtext NULL,
	ContactId					dbo.Loadtext NULL,
	AssetId						dbo.Loadtext NULL,
	CustomerLanguageCode		dbo.Loadtext NULL,
	UniqueCustomerId			dbo.Loadtext NULL,
	VehicleRegNumber			dbo.Loadtext NULL,
	VIN							dbo.Loadtext NULL,
	VehicleModel				dbo.Loadtext NULL,
	VehicleDerivative			dbo.Loadtext NULL,
	VehicleMileage				dbo.Loadtext NULL,
	VehicleMonthsinService		dbo.Loadtext NULL,
	CustomerTitle				dbo.Loadtext NULL,
	CustomerInitial				dbo.Loadtext NULL,
	CustomerFirstName			dbo.Loadtext NULL,
	CustomerLastName			dbo.Loadtext NULL,
	AddressLine1				dbo.Loadtext NULL,
	AddressLine2				dbo.Loadtext NULL,
	AddressLine3				dbo.Loadtext NULL,
	AddressLine4				dbo.Loadtext NULL,
	City						dbo.Loadtext NULL,
	County						dbo.Loadtext NULL,
	Country						dbo.Loadtext NULL,
	PostalCode					dbo.Loadtext NULL,
	PhoneMobile					dbo.Loadtext NULL,
	PhoneHome					dbo.Loadtext NULL,
	EmailAddress				dbo.Loadtext NULL,
	CompanyName					dbo.Loadtext NULL,
	RowId						dbo.Loadtext NULL,
	CaseNumber					dbo.Loadtext NULL,
	SRCreatedDate				dbo.Loadtext NULL,
	SRClosedDate				dbo.Loadtext NULL,
	Owner						dbo.Loadtext NULL,
	ClosedBy					dbo.Loadtext NULL,
	Type						dbo.Loadtext NULL,
	PrimaryReasonCode			dbo.Loadtext NULL,
	SecondaryReasonCode			dbo.Loadtext NULL,
	ConcernAreaCode				dbo.Loadtext NULL,
	SymptomCode					dbo.Loadtext NULL,
	NoOfSelectedContacts		dbo.Loadtext NULL,
	Rule1						dbo.Loadtext NULL,
	Rule2						dbo.Loadtext NULL,
	C05							dbo.Loadtext NULL,
	C07							dbo.Loadtext NULL,
	C15							dbo.Loadtext NULL,
	T06							dbo.Loadtext NULL,
	T08							dbo.Loadtext NULL,
	T13							dbo.Loadtext NULL,
	Rule5						dbo.Loadtext NULL,
	Rule6						dbo.Loadtext NULL,
	Rule7a						dbo.Loadtext NULL,
	Rule7b						dbo.Loadtext NULL,
	Rule8						dbo.Loadtext NULL,
	
	ConvertedSRCreatedDate		[datetime2](7)  NULL,
	ConvertedSRClosedDate		[datetime2](7)  NULL,
	PreferredLanguageID			int			 NULL,
	SampleTriggeredSelectionReqID int		 NULL,
	COMPLETE_SUPPRESSION		dbo.Loadtext NULL,
	SUPPRESSION_EMAIL			dbo.Loadtext NULL,
	SUPPRESSION_PHONE			dbo.Loadtext NULL,
	SUPPRESSION_MAIL			dbo.Loadtext NULL
);

