ALTER TABLE [Canada].[Sales_FilteredRecords]
    ADD CONSTRAINT [PK_CanadaSales_FilteredRecords] PRIMARY KEY CLUSTERED (AuditID ASC, [PhysicalRowID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

