CREATE TABLE [CustomerUpdateFeeds].[CustomerUpdateFeed] (
    [PartyID]                                 INT            NOT NULL,
    [CASEID]                                  INT            NOT NULL,
    [ActionDate]                              DATETIME       NULL,
    [CustomerUpdate_AuditItemID]              BIGINT         NULL,
    [OrganisationUpdate_AuditItemID]          BIGINT         NULL,
    [EmailAddressUpdate_AuditItemID]          BIGINT         NULL,
    [TelephoneUpdate_AuditItemID]             BIGINT         NULL,
    [RegistrationUpdate_AuditItemID]          BIGINT         NULL,
    [PostalAddressUpdate_AuditItemID]         BIGINT         NULL,
    [DealerUpdate_AuditItemID]                BIGINT         NULL,
    [TransactionType]                         CHAR (1)       NULL,
    [DealerCode]                              NVARCHAR (100) NULL,
    [DealerShortName]                         NVARCHAR (150) NULL,
    [Market]                                  NVARCHAR (75)  NULL,
    [Outlettype]                              NVARCHAR (45)  NULL,
    [Questionnaire]                           NVARCHAR (100) NULL,
    [QuestionnaireOrderItemId]                INT            NULL,
    [ModelDescription]                        NVARCHAR (150) NULL,
    [RegistrationNumber]                      NVARCHAR (200) NULL,
    [Manufacturer]                            NVARCHAR (20)  NULL,
    [ManufacturerPartyId]                     INT            NULL,
    [VIN]                                     NVARCHAR (200) NULL,
    [VehicleId]                               INT            NULL,
    [ClosureDate]                             DATETIME       NULL,
    [Title]                                   NVARCHAR (200) NULL,
    [CustomerFirstName]                       NVARCHAR (100) NULL,
    [CustomerSecondLastName]                  NVARCHAR (100) NULL,
    [CustomerLastName]                        NVARCHAR (100) NULL,
    [PassportID]                              NVARCHAR (50)  NULL,
    [OrganisationName]                        NVARCHAR (510) NULL,
    [AddressLine1]                            NVARCHAR (150) NULL,
    [AddressLine2]                            NVARCHAR (150) NULL,
    [AddressLine3]                            NVARCHAR (150) NULL,
    [AddressLine4]                            NVARCHAR (150) NULL,
    [AddressLine5]                            NVARCHAR (150) NULL,
    [Town]                                    NVARCHAR (100) NULL,
    [Region]                                  NVARCHAR (100) NULL,
    [Country]                                 NVARCHAR (60)  NULL,
    [PostCode]                                NVARCHAR (60)  NULL,
    [HomeContactNumber]                       NVARCHAR (35)  NULL,
    [WorkContactNumber]                       NVARCHAR (35)  NULL,
    [MobileContactNumber]                     NVARCHAR (35)  NULL,
    [ElectronicAddress]                       NVARCHAR (510) NULL,
    [NEW_DealerCode]                          NVARCHAR (100) NULL,
    [NEW_DealerShortName]                     NVARCHAR (150) NULL,
    [NEW_RegistrationNumber]                  NVARCHAR (200) NULL,
    [NEW_Title]                               NVARCHAR (200) NULL,
    [NEW_CustomerFirstName]                   NVARCHAR (100) NULL,
    [NEW_CustomerSecondLastName]              NVARCHAR (100) NULL,
    [NEW_CustomerLastName]                    NVARCHAR (100) NULL,
    [NEW_PassportID]                          NVARCHAR (50)  NULL,
    [NEW_OrganisationName]                    NVARCHAR (510) NULL,
    [NEW_AddressContactMechanismID]           INT            NULL,
    [NEW_AddressLine1]                        NVARCHAR (150) NULL,
    [NEW_AddressLine2]                        NVARCHAR (150) NULL,
    [NEW_AddressLine3]                        NVARCHAR (150) NULL,
    [NEW_AddressLine4]                        NVARCHAR (150) NULL,
    [NEW_AddressLine5]                        NVARCHAR (150) NULL,
    [NEW_Town]                                NVARCHAR (100) NULL,
    [NEW_Region]                              NVARCHAR (100) NULL,
    [NEW_Country]                             NVARCHAR (60)  NULL,
    [NEW_PostCode]                            NVARCHAR (60)  NULL,
    [NEW_AddressContactMechanismTypeID]       INT            NULL,
    [NEW_ContactNumber]                       NVARCHAR (35)  NULL,
    [NEW_WorkContactNumber]                   NVARCHAR (35)  NULL,
    [NEW_MobileContactNumber]                 NVARCHAR (35)  NULL,
    [NEW_ContactNumberTYPE_Text]              NVARCHAR (50)  NULL,
    [NEW_NumberContactMechanismPurposeTypeID] INT            NULL,
    [NEW_EmailAddress]                        NVARCHAR (510) NULL,
    [NEW_EmailAddressTYPE_Text]               NVARCHAR (50)  NULL,
    [NEW_EmailAddressTYPE_ID]                 INT            NULL,
    [NEW_EmailAddress_ContactMechanismID]     INT            NULL,
    [EmailValidityFLAG]                       INT            NULL
);

