CREATE TABLE [CRM].[LostLeadModels]
(
	OtherModel						NVARCHAR(40) NULL,
	LEAD_BRAND						NVARCHAR(40) NULL,
	LEAD_MODEL_OF_INTEREST			NVARCHAR(40) NULL,
	LEAD_MODEL_OF_INTEREST_CODE		NVARCHAR(40) NULL

)
