CREATE FUNCTION dbo.udfGetTimestampString
(
	@Date DATETIME2(7)
)
RETURNS CHAR(15)
AS

BEGIN

	DECLARE @TimeStampString CHAR(15)
	
	SELECT @TimeStampString = CAST(DATEPART(YY, @Date) AS CHAR(4))
		+ CASE WHEN LEN(CAST(DATEPART(M, @Date) AS VARCHAR(2))) = 1 THEN '0' + CAST(DATEPART(M, @Date) AS VARCHAR(2)) ELSE CAST(DATEPART(M, @Date) AS VARCHAR(2)) END
		+ CASE WHEN LEN(CAST(DATEPART(D, @Date) AS VARCHAR(2))) = 1 THEN '0' + CAST(DATEPART(D, @Date) AS VARCHAR(2)) ELSE CAST(DATEPART(D, @Date) AS VARCHAR(2)) END
		+ '_'
		+ CASE WHEN LEN(CAST(DATEPART(HH, @Date) AS VARCHAR(2))) = 1 THEN '0' + CAST(DATEPART(HH, @Date) AS VARCHAR(2)) ELSE CAST(DATEPART(HH, @Date) AS VARCHAR(2)) END
		+ CASE WHEN LEN(CAST(DATEPART(MI, @Date) AS VARCHAR(2))) = 1 THEN '0' + CAST(DATEPART(MI, @Date) AS VARCHAR(2)) ELSE CAST(DATEPART(MI, @Date) AS VARCHAR(2)) END
		+ CASE WHEN LEN(CAST(DATEPART(S, @Date) AS VARCHAR(2))) = 1 THEN '0' + CAST(DATEPART(S, @Date) AS VARCHAR(2)) ELSE CAST(DATEPART(S, @Date) AS VARCHAR(2)) END
		
	RETURN @TimeStampString

END


