CREATE TABLE [Audit].[CombinedOnlineOutput](
	[AuditID] [bigint] NOT NULL,
	[AuditItemID] [bigint] NOT NULL,
	[SelectionOutputTypeID] [tinyint] NOT NULL,
	[CaseID] [int] NULL,
	[SurveyTypeID] [smallint] NULL,
	[ModelCode] BIGINT NULL,
	[ModelDescription] [varchar](100) NULL,
	[ModelYear] VARCHAR(50) NULL,
	[ManufacturerID] [smallint] NULL,
	[Manufacturer] [nvarchar](1020) NULL,
	[CarRegistration] [nvarchar](2000) NULL,
	[VIN] [nvarchar](2000) NULL,
	[ModelVariantCode] [smallint] NULL,
	[ModelVariantDescription] [varchar](50) NULL,
	[PartyID] [int] NULL,
	[Title] [nvarchar](2000) NULL,
	[Initial] [nvarchar](2000) NULL,
	[LastName] [nvarchar](2000) NULL,
	[FullName] [nvarchar](2000) NULL,
	[DearName] [nvarchar](2000) NULL,
	[CompanyName] [nvarchar](2000) NULL,
	[Address1] [nvarchar](2000) NULL,
	[Address2] [nvarchar](2000) NULL,
	[Address3] [nvarchar](2000) NULL,
	[Address4] [nvarchar](2000) NULL,
	[Address5] [nvarchar](2000) NULL,
	[Address6] [nvarchar](2000) NULL,
	[Address7] [nvarchar](2000) NULL,
	[Address8] [nvarchar](2000) NULL,
	[Country] [varchar](200) NULL,
	[CountryID] [smallint] NULL,
	[EmailAddress] [nvarchar](2000) NULL,
	[HomeNumber] [varchar](70) NULL,
	[WorkNumber] [varchar](70) NULL,
	[MobileNumber] [varchar](70) NULL,
	[CustomerUniqueID] [nvarchar](100) NULL,
	[VersionCode] [varchar](200) NULL,
	[LanguageID] [smallint] NULL,
	[GenderID] [smallint] NULL,
	[EventTypeID] [smallint] NULL,
	[EventDate] [varchar](10) NULL,
	[Password] [varchar](10) NULL,
	[IType] [varchar](10) NULL,
	[SelectionDate] [nvarchar](20) NULL,
	[Week] [int] NULL,
	[Expired] [datetime2](7) NULL,
	[CampaignID] [nvarchar](200) NULL,
	[Test] [smallint] NULL,
	[DealerPartyID] [int] NULL,
	[ReportingDealerPartyID] [int] NULL,
	[DealerName] [nvarchar](300) NULL,
	[DealerCode] [nvarchar](40) NULL,
	[GlobalDealerCode] [nvarchar](40) NULL,
	[BusinessRegion] [varchar](150) NULL,
	[OwnershipCycle] [smallint] NULL,
	[EmailSignator] [nvarchar](2000) NULL,
	[EmailSignatorTitle] [nvarchar](2000) NULL,
	[EmailContactText] [nvarchar](2000) NULL,
	[EmailCompanyDetails] [nvarchar](2000) NULL,
	[JLRPrivacyPolicy] [nvarchar](2000) NULL,
	[JLRCompanyName] [nvarchar](2000) NULL,
	[UnknownLanguage] [smallint] NULL,
	[BilingualFlag] [smallint] NULL,
	[BilingualLanguageID] [smallint] NULL,
	[DearNameBilingual] [nvarchar](1000) NULL,
	[EmailSignatorTitleBilingual] [nvarchar](1000) NULL,
	[EmailContactTextBilingual] [nvarchar](2000) NULL,
	[EmailCompanyDetailsBilingual] [nvarchar](2000) NULL,
	[JLRPrivacyPolicyBilingual] [nvarchar](2000) NULL,
	[EmployeeCode] [nvarchar](100) NULL,
	[EmployeeName] [nvarchar](100) NULL,
	[CRMSalesmanCode] [nvarchar](100) NULL,
	[CRMSalesmanName] [nvarchar](100) NULL,
	[RockarDealer] [smallint] NULL,
	[SVOTypeID] NVARCHAR(10) NULL,
	[SVODealer] NVARCHAR(10) NULL,
	[VistaContractOrderNumber] [nvarchar](100) NULL,
	[DealerNumber] [nvarchar](100) NULL,
	[FOBCode] NVARCHAR(10) NULL,
	[HotTopicCodes] [nvarchar](100) NULL,
	[ServiceTechnicianID] [nvarchar](100) NULL,
	[ServiceTechnicianName] [nvarchar](100) NULL,
	[ServiceAdvisorID] [nvarchar](100) NULL,
	[ServiceAdvisorName] [nvarchar](100) NULL,
	[RepairOrderNumber] [nvarchar](100) NULL,
	[ServiceEventType] [smallint] NULL,
	[Approved] [nvarchar](100) NULL,
	[BreakdownDate] [nvarchar](10) NULL,
	[BreakdownCountry] [nvarchar](100) NULL,
	[BreakdownCountryID] NVARCHAR(10) NULL,
	[BreakdownCaseID] [nvarchar](100) NULL,
	[CarHireStartDate] [nvarchar](30) NULL,
	[ReasonForHire] [nvarchar](100) NULL,
	[HireGroupBranch] [nvarchar](100) NULL,
	[CarHireTicketNumber] [nvarchar](100) NULL,
	[HireJobNumber] [nvarchar](100) NULL,
	[RepairingDealer] [nvarchar](200) NULL,
	[DataSource] [nvarchar](100) NULL,
	[ReplacementVehicleMake] [nvarchar](100) NULL,
	[ReplacementVehicleModel] [nvarchar](100) NULL,
	[CarHireStartTime] [nvarchar](30) NULL,
	[RepairingDealerCountry] [nvarchar](100) NULL,
	[RoadsideAssistanceProvider] [nvarchar](100) NULL,
	[BreakdownAttendingResource] [nvarchar](100) NULL,
	[CarHireProvider] [nvarchar](100) NULL,
	[VehicleOriginCountry] [nvarchar](100) NULL,
	[CRCOwnerCode] [nvarchar](100) NULL,
	[CRCCode] [varchar](10) NULL,
	[CRCMarketCode] [varchar](10) NULL,
	[SampleYear] [nvarchar](100) NULL,
	[VehicleMileage] [nvarchar](100) NULL,
	[VehicleMonthsinService] [nvarchar](100) NULL,
	[CRCRowID] [nvarchar](100) NULL,
	[CRCSerialNumber] [nvarchar](100) NULL,
	[NSCFlag] [nvarchar](100) NULL,
	[JLREventType] [smallint] NULL,
	[DealerType] [nvarchar](100) NULL,
	[Queue] [nvarchar](100) NULL,
	[Dealer10DigitCode] NVARCHAR(10) NULL,
	[EventID]			BIGINT NULL,
    [EngineType] INT NULL, 
	[LeadVehSaleType] NVARCHAR(20) NULL, --23/08/2021 TASK 567
	[LeadOrigin] NVARCHAR(40) NULL, --23/08/2021 TASK 567
	[LegalGrounds] INT NULL, -- TASK 600 29/09/21
	[AnonymityQuestion] INT NULL, -- TASK 600 29/09/21
	[LandRoverExperienceID]			NVARCHAR(50) NULL,	--TASK 877
	[BusinessFlag]					NVARCHAR (50) NULL,	--TASK 900 -- Business & Fleet Vehicle changes 
	[CommonSaleType]				NVARCHAR (50) NULL,	--TASK 900 -- Business & Fleet Vehicle changes
    [SubBrand]						VARCHAR (50) NULL,	--TASK 1017 -- House Of Brands
	CONSTRAINT [PK_CombinedOnlineOutput] PRIMARY KEY ([AuditItemID])
)