CREATE TABLE [Audit].[InternalUpdate_DirectSalesDealerUpdate]
(
	[AuditID]												[dbo].[AuditID]	NOT NULL,
    [AuditItemID]											[dbo].[AuditItemID] NOT NULL,
	[ParentAuditItemID]										[dbo].[AuditItemID] NULL,
    [CountryID]												[dbo].[CountryID] NULL,
    [ManufacturerPartyID]									[dbo].[PartyID] NULL,
    [MatchedODSEventID]										[dbo].[EventID] NULL,
    [SalesDealerID]											[dbo].[PartyID] NULL,
	[MatchedODSVehicleID]									[dbo].[VehicleID] NULL,
	[ConvertedHandoverDate]									DATETIME2 NULL,
	[ORDER NO]												[dbo].[LoadText] NULL,
	[ORDER CREATED DATE]									[dbo].[LoadText] NULL,
	[COMMON TYPE OF SALE]									[dbo].[LoadText] NULL,
	[BRAND ORDER TYPE]										[dbo].[LoadText] NULL,
	[PARTNER UNIQUE ID]										[dbo].[LoadText] NULL,
	[VIN]													[dbo].[LoadText] NULL,
	[SHORT VIN]												[dbo].[LoadText] NULL,
	[BUILD PERIOD REFERENCE]								[dbo].[LoadText] NULL,
	[ACCEPTED BUILD DATE]									[dbo].[LoadText] NULL,
	[CURRENT PLANNED BUILD DATE]							[dbo].[LoadText] NULL,
	[REQUESTED DELIVERY DATE]								[dbo].[LoadText] NULL,
	[ACCEPTED DELIVERY DATE]								[dbo].[LoadText] NULL,
	[CURRENT PLANNED DELIVERY DATE]							[dbo].[LoadText] NULL,
	[FINAL DESTINATION CODE]								[dbo].[LoadText] NULL,
	[FACTORY COMPLETE DATE]									[dbo].[LoadText] NULL,
	[CUSTOMER HANDOVER DATE]								[dbo].[LoadText] NULL,
	[CONTRACT DATE]											[dbo].[LoadText] NULL,
	[CONTRACT NUMBER]										[dbo].[LoadText] NULL,
	[CUSTOMER ID]											[dbo].[LoadText] NULL,
	[SALESMAN]												[dbo].[LoadText] NULL,
	[SALES TYPE CODE]										[dbo].[LoadText] NULL,
	[SELLING PARTNER UNIQUE ID]								[dbo].[LoadText] NULL,
	[REGISTRATION DATE]										[dbo].[LoadText] NULL,
	[REGISTRATION NUMBER]									[dbo].[LoadText] NULL,
	[INVOICE NUMBER]										[dbo].[LoadText] NULL,
	[DEALER INVOICE TIMESTAMP]								[dbo].[LoadText] NULL,
	[REFERENCE DATE]										[dbo].[LoadText] NULL,
	[BRAND]													[dbo].[LoadText] NULL,
	[MODEL DESCRIPTION]										[dbo].[LoadText] NULL,
	[MODEL YEAR CODE]										[dbo].[LoadText] NULL,
	[MODEL YEAR DESCRIPTION]								[dbo].[LoadText] NULL,
	[DERIVATIVE CODE]										[dbo].[LoadText] NULL,
	[DERIVATIVE DESCRIPTION]								[dbo].[LoadText] NULL,
	[TRIM CODE]												[dbo].[LoadText] NULL,
	[TRIM DESCRIPTION]										[dbo].[LoadText] NULL,
	[COLOUR CODE]											[dbo].[LoadText] NULL,
	[COLOUR DESCRIPTION]									[dbo].[LoadText] NULL,
	Processed												BIT NOT NULL,
	ProcessedDate											DATETIME2 NULL
)