CREATE TABLE [Audit].[SVOLookup]
(
	[AuditItemID] [bigint] NOT NULL,
	[Vin] [nvarchar](2000)  NOT NULL,
	[ShortVin] [nvarchar](2000) NULL,
	[ModelYearDescription] [nvarchar](2000) NULL,
	[ModelDescription] [nvarchar](2000) NULL,
	[ExteriorColourDescription] [nvarchar](2000) NULL,
	[TrimDescription] [nvarchar](2000) NULL,
	[TransmissionDescription] [nvarchar](2000) NULL,
	[TrimPackDescription] [nvarchar](2000) NULL,
	[VistaMarketDesc] [nvarchar](2000) NULL,
	[DealerCICode] [nvarchar](2000) NULL,
	[PartnerUniqueId] [nvarchar](2000) NULL,
	[PartnerUniqueIdDesc] [nvarchar](2000) NULL,
	[CommonTypeOfSaleDesc] [nvarchar](2000) NULL,
	[CommonOrderNo] [nvarchar](2000) NULL,
	[NscOrderNumber] [nvarchar](2000) NULL,
	[FactoryOrderNumber] [nvarchar](2000) NULL,
	[CommonStatusPointDesc] [nvarchar](2000) NULL,
	[BuildDate] [nvarchar](2000) NULL,
	[DeliveredDate] [nvarchar](2000) NULL,
	[CustomerHandoverDate] [nvarchar](2000) NULL,
	[FeatureId] [nvarchar](2000) NULL,
	[FeatureDesc] [nvarchar](2000) NULL,
	[SaleType] [nvarchar](2000) NULL,
	[SVOTypeID] [int] NULL,
	[Paint]	[nvarchar](2000) NULL			
)
