CREATE NONCLUSTERED INDEX [IX_Service_WithResponses_AuditID]
    ON [China].[Service_WithResponses](AuditID ASC)
    INCLUDE(AuditItemID, CaseID) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);

