CREATE NONCLUSTERED INDEX [IX_General_Enquiry_ACCT_MKT_PERM_ITEM_AuditID_ACCT_MKT_PERM_Id]
	ON [CRM].[General_Enquiry_ACCT_MKT_PERM_ITEM] ([AuditID],[ACCT_MKT_PERM_Id])
	INCLUDE ([COMMCHANNEL],[CONSENT])