ALTER TABLE [Warranty].[WarrantyEvents]
    ADD CONSTRAINT [PK_WarrantyEvents] PRIMARY KEY CLUSTERED ([WarrantyID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

