ALTER TABLE [dbo].[VWT]
    ADD CONSTRAINT [PK_VWT] PRIMARY KEY CLUSTERED ([VWTID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

