ALTER TABLE [SampleReceipt].[EmailReportOutputs]
    ADD CONSTRAINT [PK_EmailReportOutputs] PRIMARY KEY CLUSTERED (EmailListID ASC, ReportOutputID ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);
