CREATE TABLE [SampleReport].[GlobalReportDealerRegionDistinctEventAggregate](
	[ReportYear] [int] NOT NULL,
	[ReportMonth] [int]  NOT NULL,
	[SummaryType] [nvarchar] (10) NOT NULL,
	[Brand] [nvarchar](510)  NOT NULL,
	[Market] [varchar](200)  NOT NULL,
	[Questionnaire] [varchar](255)  NOT NULL,
	[UpdatedTime] [datetime] DEFAULT GETDATE(),
	[SuperNationalRegion] [nvarchar](250) NOT NULL,
	[BusinessRegion] [nvarchar](250) NOT NULL,
	[SubNationalTerritory] [nvarchar](255) NOT NULL,
	[SubNationalRegion] [nvarchar](255) NOT NULL,
	[DealerCode] [nvarchar](20) NOT NULL,
	[DealerCodeGDD] [nvarchar](20) NULL,
	[DealerName] [nvarchar](150) NOT NULL,
	[EventsLoaded] [int] NULL,
	[SuppliedEmail] [int] NULL,
	[UsableEvents] [int] NULL,
	[InvitesSent] [int] NULL,
	[Bouncebacks] [int] NULL,
	[Responded] [int] NULL,
	[EmailInvites] [int] NULL,
	[SMSInvites] [int] NULL,
	[PostalInvites] [int] NULL,
	[PhoneInvites] [int] NULL,
	[SoftBounce] [int] NULL,
	[HardBounce] [int] NULL
) ;
