CREATE TABLE [SampleReport].[GlobalReportDistinctEventSummary](
	[ReportYear] [int] NOT NULL ,
	[ReportMonth] [int]  NOT NULL,
	[SummaryType] [varchar] (10) NOT NULL,
	[Brand] [nvarchar](510) NOT NULL ,
	[Market] [varchar](200) NOT NULL,
	[Questionnaire] [varchar](255)  NOT NULL,
	[UpdatedTime] [datetime] DEFAULT GETDATE(),
	[SuperNationalRegion] [nvarchar](250) NULL,
	[BusinessRegion] [nvarchar](250) NULL,
	[EventsLoaded] [int] NULL,
	[SuppliedEmail] [int] NULL,
	[UsableEvents] [int] NULL,
	[InvitesSent] [int] NULL,
	[Bouncebacks] [int] NULL,
	[Responded] [int] NULL,
	[EmailInvites] [int] NULL,
	[SMSInvites] [int] NULL,
	[PostalInvites] [int] NULL,
	[PhoneInvites] [int] NULL,
	[FeedType] [varchar] (30) NULL,
	[10YrVehicleParc] [int] null,
	[SoftBounce] [int] NULL,
	[HardBounce] [int] NULL
) ;
