CREATE TABLE [SampleReport].[IndividualRowsEventsCombined](
	[ReportDate] [datetime] NOT NULL,
	[SuperNationalRegion] [nvarchar](250) NULL,
	[BusinessRegion] [nvarchar](250) NULL,
	[DealerMarket] [nvarchar](255) NULL,
	[SubNationalRegion] [nvarchar](255) NULL,
	[CombinedDealer] [nvarchar](255) NULL,
	[DealerName] [nvarchar](150) NULL,
	[DealerCode] [nvarchar](20) NULL,
	[DealerCodeGDD] [nvarchar](20) NULL,
	[FullName] [nvarchar](500) NULL,
	[OrganisationName] [nvarchar](510) NULL,
	[AnonymityDealer] [int] NULL,
	[AnonymityManufacturer] [int] NULL,
	[CaseCreationDate] [datetime2](7) NULL,
	[CaseStatusType] [varchar](100) NULL,
	[CaseOutputType] [varchar](100) NULL,
	[SentFlag] [int] NULL,
	[SentDate] [datetime2](7) NULL,
	[RespondedFlag] [int] NULL,
	[ClosureDate] [datetime2](7) NULL,
	[DuplicateRowFlag] [int] NULL,
	[BouncebackFlag] [int] NULL,
	[UsableFlag] [int] NULL,
	[ManualRejectionFlag] [int] NULL,
	[FileName] [varchar](100) NULL,
	[FileActionDate] [datetime] NULL,
	[FileRowCount] [int] NULL,
	[LoadedDate] [datetime2](7) NOT NULL,
	[AuditID] [bigint] NOT NULL,
	[AuditItemID] [bigint] NOT NULL,
	[MatchedODSPartyID] [bigint] NOT NULL,
	[MatchedODSPersonID] [bigint] NOT NULL,
	[LanguageID] [bigint] NOT NULL,
	[PartySuppression] [bigint] NOT NULL,
	[MatchedODSOrganisationID] [bigint] NOT NULL,
	[MatchedODSAddressID] [bigint] NOT NULL,
	[CountryID] [bigint] NULL,
	[PostalSuppression] [int] NOT NULL,
	[EmailSuppression] [int] NOT NULL,
	[MatchedODSVehicleID] [bigint] NOT NULL,
	[ODSRegistrationID] [bigint] NULL,
	[MatchedODSModelID] [int] NULL,
	[OwnershipCycle] [int] NULL,
	[MatchedODSEventID] [bigint] NOT NULL,
	[ODSEventTypeID] [int] NULL,
	[WarrantyID] [bigint] NULL,
	[Brand] [nvarchar](510) NULL,
	[Market] [varchar](200) NULL,
	[Questionnaire] [varchar](255) NULL,
	[QuestionnaireRequirementID] [int] NULL,
	[SuppliedName] [int] NOT NULL,
	[SuppliedAddress] [int] NOT NULL,
	[SuppliedPhoneNumber] [int] NOT NULL,
	[SuppliedMobilePhone] [int] NOT NULL,
	[SuppliedEmail] [int] NOT NULL,
	[SuppliedVehicle] [int] NOT NULL,
	[SuppliedRegistration] [int] NOT NULL,
	[SuppliedEventDate] [int] NOT NULL,
	[EventDateOutOfDate] [int] NOT NULL,
	[EventNonSolicitation] [int] NOT NULL,
	[PartyNonSolicitation] [int] NOT NULL,
	[UnmatchedModel] [int] NOT NULL,
	[UncodedDealer] [int] NOT NULL,
	[EventAlreadySelected] [int] NOT NULL,
	[NonLatestEvent] [int] NOT NULL,
	[InvalidOwnershipCycle] [int] NOT NULL,
	[RecontactPeriod] [int] NOT NULL,
	[RelativeRecontactPeriod] [int] NULL,
	[InvalidVehicleRole] [int] NOT NULL,
	[CrossBorderAddress] [int] NOT NULL,
	[CrossBorderDealer] [int] NOT NULL,
	[ExclusionListMatch] [int] NOT NULL,
	[InvalidEmailAddress] [int] NOT NULL,
	[BarredEmailAddress] [int] NOT NULL,
	[BarredDomain] [int] NOT NULL,
	[OtherReasonForNonSelection] [int] NULL,
	[CaseID] [int] NULL,
	[SampleRowProcessed] [int] NULL,
	[SampleRowProcessedDate] [datetime2](7) NULL,
	[WrongEventType] [int] NOT NULL,
	[MissingStreet] [int] NOT NULL,
	[MissingPostcode] [int] NOT NULL,
	[MissingEmail] [int] NOT NULL,
	[MissingTelephone] [int] NOT NULL,
	[MissingStreetAndEmail] [int] NOT NULL,
	[MissingTelephoneAndEmail] [int] NOT NULL,
	[MissingMobilePhone] [int] NOT NULL,
	[MissingMobilePhoneAndEmail] [int] NOT NULL,
	[MissingPartyName] [int] NOT NULL,
	[MissingLanguage] [int] NOT NULL,
	[InvalidModel] [int] NOT NULL,
	[InvalidManufacturer] [int] NOT NULL,
	[InternalDealer] [int] NOT NULL,
	[RegistrationNumber] [nvarchar](100) NULL,
	[RegistrationDate] [datetime2](7) NULL,
	[VIN] [nvarchar](50) NULL,
	[OutputFileModelDescription] [varchar](50) NULL,
	[EventDate] [datetime2](7) NULL,
	[SampleEmailAddress] [dbo].[EmailAddress] NULL,
	[CaseEmailAddress] [dbo].[EmailAddress] NULL,
	[PreviousEventBounceBack] [int] NOT NULL,
	[EventDateTooYoung] [int] NOT NULL,
	[AFRLCode] [nvarchar](50) NULL,
	[DealerExclusionListMatch] [int] NOT NULL,
	[PhoneSuppression] [int] NOT NULL,
	[SalesType] [nvarchar](50) NULL,
	[InvalidAFRLCode] [int] NOT NULL,
	[InvalidSalesType] [int] NOT NULL,
	[AgentCodeFlag] [int] NULL,
	[DataSource] [nvarchar](50) NULL,
	[HardBounce] [int] NULL,
	[SoftBounce] [int] NULL,
	[Unsubscribes] [int] NULL,
	[DateOfLeadCreation] [nvarchar](50) NULL,
	[PrevSoftBounce] [int] NULL,
	[PrevHardBounce] [int] NULL,
	[ServiceTechnicianID] [nvarchar](400) NULL,
	[ServiceTechnicianName] [nvarchar](400) NULL,
	[ServiceAdvisorName] [nvarchar](400) NULL,
	[ServiceAdvisorID] [nvarchar](400) NULL,
	[CRMSalesmanName] [nvarchar](400) NULL,
	[CRMSalesmanCode] [nvarchar](400) NULL,
	[SubNationalTerritory] [nvarchar](255) NULL,
	[FOBCode] [int] NULL,
	[ContactPreferencesSuppression] [int] NULL,
	[ContactPreferencesPartySuppress] [int] NULL,
	[ContactPreferencesEmailSuppress] [int] NULL,
	[ContactPreferencesPhoneSuppress] [int] NULL,
	[ContactPreferencesPostalSuppress] [int] NULL,
	[SVCRMSalesType] [nvarchar](40) NULL,
	[SVCRMInvalidSalesType] [int] NULL,
	[DealNumber] [nvarchar](200) NULL,
	[RepairOrderNumber] [nvarchar](200) NULL,
	[VistaCommonOrderNumber] [nvarchar](35) NULL,
	[SalesEmployeeCode] [nvarchar](400) NULL,
	[SalesEmployeeName] [nvarchar](400) NULL,
	[ServiceEmployeeCode] [nvarchar](400) NULL,
	[ServiceEmployeeName] [nvarchar](400) NULL,
	[RecordChanged] [int] NULL,
	[PDIFlagSet] [int] NULL,
	[OriginalPartySuppression] [int] NULL,
	[OriginalPostalSuppression] [int] NULL,
	[OriginalEmailSuppression] [int] NULL,
	[OriginalPhoneSuppression] [int] NULL,
	[OtherExclusion] [int] NULL,
	[OverrideFlag] [int] NULL,
	[GDPRflag] [int] NULL,
	[SelectionPostalID] [int] NULL,
	[SelectionEmailID] [int] NULL,
	[SelectionPhoneID] [int] NULL,
	[SelectionLandlineID] [int] NULL,
	[SelectionMobileID] [int] NULL,
	[SelectionEmail] [nvarchar](510) NULL,
	[SelectionPhone] [nvarchar](70) NULL,
	[SelectionLandline] [nvarchar](70) NULL,
	[SelectionMobile] [nvarchar](70) NULL,
	[ContactPreferencesModel] [varchar](50) NULL,
	[ContactPreferencesPersist] [int] NULL,
	[InvalidDateOfLastContact] [int] NULL,
	[MatchedODSPrivEmailAddressID] [int] NULL,
	[SamplePrivEmailAddress] [dbo].[EmailAddress] NULL,
	[EmailExcludeBarred] [int] NULL,
	[EmailExcludeGeneric] [int] NULL,
	[CompanyExcludeBodyShop] [int] NULL,
	[CompanyExcludeLeasing] [int] NULL,
	[CompanyExcludeFleet] [int] NULL,
	[CompanyExcludeBarredCo] [int] NULL,
	[EmailExcludeInvalid] [int] NULL,
	[OutletPartyID] [int] NULL,
	[Dealer10DigitCode] [nvarchar](10) NULL,
	[OutletFunction] [nvarchar](25) NULL,
	[RoadsideAssistanceProvider] [nvarchar](4000) NULL,
	[CRC_Owner] [nvarchar](4000) NULL,
	[ClosedBy] [nvarchar](4000) NULL,
	[Owner] [nvarchar](4000) NULL,
	[CountryIsoAlpha2] [char](2) NULL,
	[CRCMarketCode] [nvarchar](4000) NULL,
	[InvalidDealerBrand] [int] NULL,
	[SubBrand] [varchar](50) NULL,
	[ModelCode] [int] NULL,
	[LeadVehSaleType] [nvarchar](20) NULL,
	[ModelVariant] [nvarchar](50) NULL,
	[NoMatch_CRCAgent] [int] NULL,
	[NoMatch_InviteBMQ] [int] NULL,
	[NoMatch_InviteLanguage] [int] NULL,
	[DedupeHistoric] [int] NULL,
	[MedalliaSent] [int] NULL
) ON [PRIMARY]
GO

