CREATE NONCLUSTERED INDEX [IX_Audit_VehiclePartyRoleEvents_AuditItemID]
ON [Audit].[VehiclePartyRoleEvents]
(
	[AuditItemID] ASC
)
INCLUDE ( 	[PartyID],
			[VehicleRoleTypeID]) 
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
