CREATE NONCLUSTERED INDEX [IX_Audit_AdditionalInfoSales_EventID_SalesmanInfo] ON [Audit].[AdditionalInfoSales]
(
	[EventID] ASC
)
INCLUDE (Salesman, SalesmanCode)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 88)

