CREATE INDEX [IX_CRC_WithResponses_AuditItemID]
    ON [China].[CRC_WithResponses](AuditItemID ASC)
	INCLUDE([CaseID]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);


