CREATE TRIGGER [DealerManagement].[TR_D_vwDA_DEALERS_JLRCSP_UPDATE_PAGCode_InvalidEntries] 
ON	[DealerManagement].[vwDA_DEALERS_JLRCSP_UPDATE_PAGCode_InvalidEntries]
	INSTEAD OF DELETE
	AS SET NOCOUNT ON

	-- ROLLBACK ON ERROR
	SET XACT_ABORT ON
	
	-- DELETE ENTRIES
	
	BEGIN TRAN
	
		DELETE FROM DealerManagement.vwDA_DEALERS_JLRCSP_UPDATE_PAGCode_InvalidEntries
		WHERE IP_PAGCodeChangeID IN (SELECT IP_PAGCodeChangeID FROM deleted)
	
	COMMIT TRAN
