CREATE NONCLUSTERED INDEX [IX_VWT_MatchedODSOrganisationID]
    ON [dbo].[VWT]([MatchedODSOrganisationID] ASC)
    INCLUDE([AuditItemID], [OrganisationParentAuditItemID], [OrganisationName], [MatchedODSAddressID]) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);

