CREATE VIEW [CustomerUpdateFeeds].[vwReporting]
AS
SELECT
	cast(TransactionType as nvarchar(500)) as TransactionType,
	cast(DealerCode as nvarchar(500)) as DealerCode ,
	cast(DealerShortName as nvarchar(500)) as DealerShortName ,
	cast(ModelDescription as nvarchar(500)) as ModelDescription,
	cast(RegistrationNumber as nvarchar(500)) as RegistrationNumber,
	cast(VIN as nvarchar(500)) as VIN,
	cast(ClosureDate as nvarchar(500)) as ResponseDate,
	cast(Title as nvarchar(500)) as Title,
	cast(CustomerFirstName as nvarchar(500)) as CustomerFirstName,
	cast(CustomerSecondLastName as nvarchar(500)) as CustomerSecondLastName ,
	cast(CustomerLastName as nvarchar(500)) as CustomerLastName,
	cast(OrganisationName as nvarchar(500)) as OrganisationName,
	cast(AddressLine1 as nvarchar(500)) as AddressLine1,
	cast(AddressLine2 as nvarchar(500)) as AddressLine2,
	cast(AddressLine3 as nvarchar(500)) as AddressLine3,
	cast(AddressLine4 as nvarchar(500)) as AddressLine4,
	cast(AddressLine5 as nvarchar(500)) as AddressLine5 ,
	cast(Town as nvarchar(500)) as Town,
	cast(Region as nvarchar(500)) as Region,
	cast(PostCode as nvarchar(500)) as PostCode,
	cast(HomeContactNumber as nvarchar(500)) as HomeContactNumber,
	cast(WorkContactNumber as nvarchar(500)) as WorkContactNumber,
	cast(MobileContactNumber as nvarchar(500)) as MobileContactNumber,
	cast(EmailAddress as nvarchar(500)) as EmailAddress,
	cast(NEW_DealerCode as nvarchar(500)) as NEW_DealerCode,
	cast(NEW_DealerShortName as nvarchar(500)) as NEW_DealerShortName,
	'' as New_ModelDescription ,
	cast(NEW_RegistrationNumber as nvarchar(500)) as NEW_RegistrationNumber,
	cast(NEW_Title as nvarchar(500)) as NEW_Title,
	cast(NEW_CustomerFirstName as nvarchar(500)) as NEW_CustomerFirstName,
	cast(NEW_CustomerSecondLastName as nvarchar(500)) as NEW_CustomerSecondLastName,
	cast(NEW_CustomerLastName as nvarchar(500)) as NEW_CustomerLastName,
	cast(NEW_OrganisationName as nvarchar(500)) as NEW_OrganisationName,
	cast(NEW_AddressLine1 as nvarchar(500)) as NEW_AddressLine1,
	cast(NEW_AddressLine2 as nvarchar(500)) as NEW_AddressLine2,
	cast(NEW_AddressLine3 as nvarchar(500)) as NEW_AddressLine3,
	cast(NEW_AddressLine4 as nvarchar(500)) as NEW_AddressLine4,
	cast(NEW_AddressLine5 as nvarchar(500)) as NEW_AddressLine5,
	cast(NEW_Town as nvarchar(500)) as NEW_Town,
	cast(NEW_Region as nvarchar(500)) as NEW_Region,
	cast(NEW_Country as nvarchar(500)) as NEW_Country,
	cast(NEW_PostCode as nvarchar(500)) as NEW_PostCode,
	cast(NEW_ContactNumber as nvarchar(500)) as NEW_ContactNumber,
	cast(NEW_WorkContactNumber as nvarchar(500)) as NEW_WorkContactNumber,
	cast(NEW_MobileContactNumber as nvarchar(500)) as NEW_MobileContactNumber,
	cast(NEW_EmailAddress as nvarchar(500)) as NEW_EmailAddress ,
	cast(EmailValidityFLAG as nvarchar(500)) as EmailValidityFLAG,
	cast(Market as nvarchar(500)) as Market,
	cast(Manufacturer as nvarchar(500)) as Manufacturer,
	cast(ActionDate as nvarchar(500)) as DateProcessed,
	cast(PAGCode as nvarchar(500)) as PAGCode
	FROM CustomerUpdateFeeds.CustomerUpdateFeed