CREATE TABLE [CustomerUpdate].[PostalAddress] (
    [ID]                        INT            IDENTITY (1, 1) NOT NULL,
    [PartyID]                   dbo.PartyID            NOT NULL,
    [CaseID]                    dbo.CaseID         NOT NULL,
    [Address1]                  dbo.AddressText NULL,
    [Address2]                  dbo.AddressText NULL,
    [Address3]                  dbo.AddressText NULL,
    [Address4]                  dbo.AddressText NULL,
    [Address5]                  dbo.AddressText NULL,
    [Address6]                  dbo.AddressText NULL,
    [Address7]                  dbo.AddressText NULL,
    [BuildingName]              dbo.AddressText NULL,
    [SubStreetNumber]           dbo.AddressNumberText  NULL,
    [SubStreet]                dbo.AddressText NULL,
    [SubStreetAndNumber]        dbo.AddressText NULL,
    [StreetNumber]              dbo.AddressNumberText  NULL,
    [Street]                    dbo.AddressText NULL,
    [StreetAndNumber]           dbo.AddressText NULL,
    [SubLocality]               dbo.AddressText NULL,
    [Locality]                  dbo.AddressText NULL,
    [Town]                      dbo.AddressText NULL,
    [Region]                    dbo.AddressText NULL,
    [CountryID]                 dbo.CountryID       NULL,
    [PostCode]                  dbo.PostCode  NULL,
    [ContactMechanismID]        dbo.ContactMechanismID            NULL,
    [AuditID]                   dbo.AuditID         NULL,
    [AuditItemID]               dbo.AuditItemID         NULL,
    [CasePartyCombinationValid] BIT            NOT NULL,
    [ParentAuditItemID]         dbo.AuditItemID         NULL
);

