CREATE TRIGGER [dbo].[TR_IU_SampleQualityAndSelectionLogging]
   ON [dbo].[SampleQualityAndSelectionLogging]
   AFTER INSERT, UPDATE
AS 
BEGIN
	SET NOCOUNT ON;


    
	DECLARE @Timestamp  DATETIME 
	SET @Timestamp = GETDATE()

	-----------------------------------------------------------------------------------------------------------------------
	-- First save records which are either new OR have had something column other than the SampleRowProcessedDate changed  
	-----------------------------------------------------------------------------------------------------------------------

	;WITH CTE_ChangedOrInsertedRows	AS 
	(

		SELECT LoadedDate, AuditID, AuditItemID, PhysicalFileRow, ManufacturerID, SampleSupplierPartyID, MatchedODSPartyID, PersonParentAuditItemID, MatchedODSPersonID, LanguageID, PartySuppression, OrganisationParentAuditItemID, MatchedODSOrganisationID, AddressParentAuditItemID, MatchedODSAddressID, CountryID, PostalSuppression, AddressChecksum, MatchedODSTelID, MatchedODSPrivTelID, MatchedODSBusTelID, MatchedODSMobileTelID, MatchedODSPrivMobileTelID, MatchedODSEmailAddressID, MatchedODSPrivEmailAddressID, EmailSuppression, VehicleParentAuditItemID, MatchedODSVehicleID, ODSRegistrationID, MatchedODSModelID, OwnershipCycle, MatchedODSEventID, ODSEventTypeID, SaleDateOrig, SaleDate, ServiceDateOrig, ServiceDate, InvoiceDateOrig, InvoiceDate, WarrantyID, SalesDealerCodeOriginatorPartyID, SalesDealerCode, SalesDealerID, ServiceDealerCodeOriginatorPartyID, ServiceDealerCode, ServiceDealerID, RoadsideNetworkOriginatorPartyID, RoadsideNetworkCode, RoadsideNetworkPartyID, RoadsideDate, CRCCentreOriginatorPartyID, CRCCentreCode, CRCCentrePartyID, CRCDate, Brand, Market, Questionnaire, QuestionnaireRequirementID, StartDays, EndDays, SuppliedName, SuppliedAddress, SuppliedPhoneNumber, SuppliedMobilePhone, SuppliedEmail, SuppliedVehicle, SuppliedRegistration, SuppliedEventDate, EventDateOutOfDate, EventNonSolicitation, PartyNonSolicitation, UnmatchedModel, UncodedDealer, EventAlreadySelected, NonLatestEvent, InvalidOwnershipCycle, RecontactPeriod, InvalidVehicleRole, CrossBorderAddress, CrossBorderDealer, ExclusionListMatch, InvalidEmailAddress, BarredEmailAddress, BarredDomain, CaseID, SampleRowProcessed, 
			--SampleRowProcessedDate, 
			WrongEventType, MissingStreet, MissingPostcode, MissingEmail, MissingTelephone, MissingStreetAndEmail, MissingTelephoneAndEmail, InvalidModel, InvalidVariant, MissingMobilePhone, MissingMobilePhoneAndEmail, MissingPartyName, MissingLanguage, CaseIDPrevious, RelativeRecontactPeriod, InvalidManufacturer, InternalDealer, EventDateTooYoung, InvalidRoleType, InvalidSaleType, InvalidAFRLCode, SuppliedAFRLCode, DealerExclusionListMatch, PhoneSuppression, LostLeadDate, ContactPreferencesSuppression, NotInQuota, ContactPreferencesPartySuppress, ContactPreferencesEmailSuppress, ContactPreferencesPhoneSuppress, ContactPreferencesPostalSuppress, DealerPilotOutputFiltered, InvalidCRMSaleType, MissingLostLeadAgency, PDIFlagSet, BodyshopEventDateOrig, BodyshopEventDate, BodyshopDealerCode, BodyshopDealerID, BodyshopDealerCodeOriginatorPartyID, ContactPreferencesUnsubscribed, SelectionOrganisationID, SelectionPostalID, SelectionEmailID, SelectionPhoneID, SelectionLandlineID, SelectionMobileID, NonSelectableWarrantyEvent, IAssistanceCentreOriginatorPartyID, IAssistanceCentreCode, IAssistanceCentrePartyID, IAssistanceDate, InvalidDateOfLastContact, CQIMissingExtraVehicleFeed, GeneralEnquiryDate, MissingPerson, MissingOrganisation, InvalidDealerBrand
		FROM INSERTED
		EXCEPT
		SELECT LoadedDate, AuditID, AuditItemID, PhysicalFileRow, ManufacturerID, SampleSupplierPartyID, MatchedODSPartyID, PersonParentAuditItemID, MatchedODSPersonID, LanguageID, PartySuppression, OrganisationParentAuditItemID, MatchedODSOrganisationID, AddressParentAuditItemID, MatchedODSAddressID, CountryID, PostalSuppression, AddressChecksum, MatchedODSTelID, MatchedODSPrivTelID, MatchedODSBusTelID, MatchedODSMobileTelID, MatchedODSPrivMobileTelID, MatchedODSEmailAddressID, MatchedODSPrivEmailAddressID, EmailSuppression, VehicleParentAuditItemID, MatchedODSVehicleID, ODSRegistrationID, MatchedODSModelID, OwnershipCycle, MatchedODSEventID, ODSEventTypeID, SaleDateOrig, SaleDate, ServiceDateOrig, ServiceDate, InvoiceDateOrig, InvoiceDate, WarrantyID, SalesDealerCodeOriginatorPartyID, SalesDealerCode, SalesDealerID, ServiceDealerCodeOriginatorPartyID, ServiceDealerCode, ServiceDealerID, RoadsideNetworkOriginatorPartyID, RoadsideNetworkCode, RoadsideNetworkPartyID, RoadsideDate, CRCCentreOriginatorPartyID, CRCCentreCode, CRCCentrePartyID, CRCDate, Brand, Market, Questionnaire, QuestionnaireRequirementID, StartDays, EndDays, SuppliedName, SuppliedAddress, SuppliedPhoneNumber, SuppliedMobilePhone, SuppliedEmail, SuppliedVehicle, SuppliedRegistration, SuppliedEventDate, EventDateOutOfDate, EventNonSolicitation, PartyNonSolicitation, UnmatchedModel, UncodedDealer, EventAlreadySelected, NonLatestEvent, InvalidOwnershipCycle, RecontactPeriod, InvalidVehicleRole, CrossBorderAddress, CrossBorderDealer, ExclusionListMatch, InvalidEmailAddress, BarredEmailAddress, BarredDomain, CaseID, SampleRowProcessed, 
			--SampleRowProcessedDate, 
			WrongEventType, MissingStreet, MissingPostcode, MissingEmail, MissingTelephone, MissingStreetAndEmail, MissingTelephoneAndEmail, InvalidModel, InvalidVariant, MissingMobilePhone, MissingMobilePhoneAndEmail, MissingPartyName, MissingLanguage, CaseIDPrevious, RelativeRecontactPeriod, InvalidManufacturer, InternalDealer, EventDateTooYoung, InvalidRoleType, InvalidSaleType, InvalidAFRLCode, SuppliedAFRLCode, DealerExclusionListMatch, PhoneSuppression, LostLeadDate, ContactPreferencesSuppression, NotInQuota, ContactPreferencesPartySuppress, ContactPreferencesEmailSuppress, ContactPreferencesPhoneSuppress, ContactPreferencesPostalSuppress, DealerPilotOutputFiltered, InvalidCRMSaleType, MissingLostLeadAgency, PDIFlagSet, BodyshopEventDateOrig, BodyshopEventDate, BodyshopDealerCode, BodyshopDealerID, BodyshopDealerCodeOriginatorPartyID, ContactPreferencesUnsubscribed, SelectionOrganisationID, SelectionPostalID, SelectionEmailID, SelectionPhoneID, SelectionLandlineID, SelectionMobileID, NonSelectableWarrantyEvent, IAssistanceCentreOriginatorPartyID, IAssistanceCentreCode, IAssistanceCentrePartyID, IAssistanceDate, InvalidDateOfLastContact, CQIMissingExtraVehicleFeed, GeneralEnquiryDate, MissingPerson, MissingOrganisation, InvalidDealerBrand
		FROM DELETED
	)
	INSERT INTO [dbo].[SampleQualityAndSelectionLoggingAudit]
	(
		AuditTimestamp,
		LoadedDate, AuditID, AuditItemID, PhysicalFileRow, ManufacturerID, SampleSupplierPartyID, MatchedODSPartyID, PersonParentAuditItemID, MatchedODSPersonID, LanguageID, PartySuppression, OrganisationParentAuditItemID, MatchedODSOrganisationID, AddressParentAuditItemID, MatchedODSAddressID, CountryID, PostalSuppression, AddressChecksum, MatchedODSTelID, MatchedODSPrivTelID, MatchedODSBusTelID, MatchedODSMobileTelID, MatchedODSPrivMobileTelID, MatchedODSEmailAddressID, MatchedODSPrivEmailAddressID, EmailSuppression, VehicleParentAuditItemID, MatchedODSVehicleID, ODSRegistrationID, MatchedODSModelID, OwnershipCycle, MatchedODSEventID, ODSEventTypeID, SaleDateOrig, SaleDate, ServiceDateOrig, ServiceDate, InvoiceDateOrig, InvoiceDate, WarrantyID, SalesDealerCodeOriginatorPartyID, SalesDealerCode, SalesDealerID, ServiceDealerCodeOriginatorPartyID, ServiceDealerCode, ServiceDealerID, RoadsideNetworkOriginatorPartyID, RoadsideNetworkCode, RoadsideNetworkPartyID, RoadsideDate, CRCCentreOriginatorPartyID, CRCCentreCode, CRCCentrePartyID, CRCDate, Brand, Market, Questionnaire, QuestionnaireRequirementID, StartDays, EndDays, SuppliedName, SuppliedAddress, SuppliedPhoneNumber, SuppliedMobilePhone, SuppliedEmail, SuppliedVehicle, SuppliedRegistration, SuppliedEventDate, EventDateOutOfDate, EventNonSolicitation, PartyNonSolicitation, UnmatchedModel, UncodedDealer, EventAlreadySelected, NonLatestEvent, InvalidOwnershipCycle, RecontactPeriod, InvalidVehicleRole, CrossBorderAddress, CrossBorderDealer, ExclusionListMatch, InvalidEmailAddress, BarredEmailAddress, BarredDomain, CaseID, SampleRowProcessed, 
		SampleRowProcessedDate, 
		WrongEventType, MissingStreet, MissingPostcode, MissingEmail, MissingTelephone, MissingStreetAndEmail, MissingTelephoneAndEmail, InvalidModel, InvalidVariant, MissingMobilePhone, MissingMobilePhoneAndEmail, MissingPartyName, MissingLanguage, CaseIDPrevious, RelativeRecontactPeriod, InvalidManufacturer, InternalDealer, EventDateTooYoung, InvalidRoleType, InvalidSaleType, InvalidAFRLCode, SuppliedAFRLCode, DealerExclusionListMatch, PhoneSuppression, LostLeadDate, ContactPreferencesSuppression, NotInQuota, ContactPreferencesPartySuppress, ContactPreferencesEmailSuppress, ContactPreferencesPhoneSuppress, ContactPreferencesPostalSuppress, DealerPilotOutputFiltered, InvalidCRMSaleType, MissingLostLeadAgency, PDIFlagSet, BodyshopEventDateOrig, BodyshopEventDate, BodyshopDealerCode, BodyshopDealerID, BodyshopDealerCodeOriginatorPartyID, ContactPreferencesUnsubscribed, SelectionOrganisationID, SelectionPostalID, SelectionEmailID, SelectionPhoneID, SelectionLandlineID, SelectionMobileID, NonSelectableWarrantyEvent, IAssistanceCentreOriginatorPartyID, IAssistanceCentreCode, IAssistanceCentrePartyID, IAssistanceDate, InvalidDateOfLastContact, CQIMissingExtraVehicleFeed, GeneralEnquiryDate, MissingPerson, MissingOrganisation, InvalidDealerBrand
	)
 	SELECT @Timestamp,
		LoadedDate, AuditID, AuditItemID, PhysicalFileRow, ManufacturerID, SampleSupplierPartyID, MatchedODSPartyID, PersonParentAuditItemID, MatchedODSPersonID, LanguageID, PartySuppression, OrganisationParentAuditItemID, MatchedODSOrganisationID, AddressParentAuditItemID, MatchedODSAddressID, CountryID, PostalSuppression, AddressChecksum, MatchedODSTelID, MatchedODSPrivTelID, MatchedODSBusTelID, MatchedODSMobileTelID, MatchedODSPrivMobileTelID, MatchedODSEmailAddressID, MatchedODSPrivEmailAddressID, EmailSuppression, VehicleParentAuditItemID, MatchedODSVehicleID, ODSRegistrationID, MatchedODSModelID, OwnershipCycle, MatchedODSEventID, ODSEventTypeID, SaleDateOrig, SaleDate, ServiceDateOrig, ServiceDate, InvoiceDateOrig, InvoiceDate, WarrantyID, SalesDealerCodeOriginatorPartyID, SalesDealerCode, SalesDealerID, ServiceDealerCodeOriginatorPartyID, ServiceDealerCode, ServiceDealerID, RoadsideNetworkOriginatorPartyID, RoadsideNetworkCode, RoadsideNetworkPartyID, RoadsideDate, CRCCentreOriginatorPartyID, CRCCentreCode, CRCCentrePartyID, CRCDate, Brand, Market, Questionnaire, QuestionnaireRequirementID, StartDays, EndDays, SuppliedName, SuppliedAddress, SuppliedPhoneNumber, SuppliedMobilePhone, SuppliedEmail, SuppliedVehicle, SuppliedRegistration, SuppliedEventDate, EventDateOutOfDate, EventNonSolicitation, PartyNonSolicitation, UnmatchedModel, UncodedDealer, EventAlreadySelected, NonLatestEvent, InvalidOwnershipCycle, RecontactPeriod, InvalidVehicleRole, CrossBorderAddress, CrossBorderDealer, ExclusionListMatch, InvalidEmailAddress, BarredEmailAddress, BarredDomain, CaseID, SampleRowProcessed, 
		(SELECT SampleRowProcessedDate FROM INSERTED i WHERE i.AuditItemID = CR.AuditItemID) AS SampleRowProcessedDate, 
		WrongEventType, MissingStreet, MissingPostcode, MissingEmail, MissingTelephone, MissingStreetAndEmail, MissingTelephoneAndEmail, InvalidModel, InvalidVariant, MissingMobilePhone, MissingMobilePhoneAndEmail, MissingPartyName, MissingLanguage, CaseIDPrevious, RelativeRecontactPeriod, InvalidManufacturer, InternalDealer, EventDateTooYoung, InvalidRoleType, InvalidSaleType, InvalidAFRLCode, SuppliedAFRLCode, DealerExclusionListMatch, PhoneSuppression, LostLeadDate, ContactPreferencesSuppression, NotInQuota, ContactPreferencesPartySuppress, ContactPreferencesEmailSuppress, ContactPreferencesPhoneSuppress, ContactPreferencesPostalSuppress, DealerPilotOutputFiltered, InvalidCRMSaleType, MissingLostLeadAgency, PDIFlagSet, BodyshopEventDateOrig, BodyshopEventDate, BodyshopDealerCode, BodyshopDealerID, BodyshopDealerCodeOriginatorPartyID, ContactPreferencesUnsubscribed, SelectionOrganisationID, SelectionPostalID, SelectionEmailID, SelectionPhoneID, SelectionLandlineID, SelectionMobileID, NonSelectableWarrantyEvent, IAssistanceCentreOriginatorPartyID, IAssistanceCentreCode, IAssistanceCentrePartyID, IAssistanceDate, InvalidDateOfLastContact, CQIMissingExtraVehicleFeed, GeneralEnquiryDate, MissingPerson, MissingOrganisation, InvalidDealerBrand
	FROM CTE_ChangedOrInsertedRows CR



	-----------------------------------------------------------------------------------------------------------------------
	-- Now save ALL SampleRowProcessedDate information from the updates and inserts, seperately
	-----------------------------------------------------------------------------------------------------------------------
	
	INSERT INTO [dbo].[SampleProcessedLoggingAudit]  (AuditTimestamp, AuditID, AuditItemID, CaseID, SampleRowProcessed, SampleRowProcessedDate, SelectionPoint)
	SELECT @Timestamp, 
			i.AuditID, 
			i.AuditItemID, 
			i.CaseID, 
			i.SampleRowProcessed, 
			i.SampleRowProcessedDate,
			CASE WHEN d.CaseID IS NULL AND i.CaseID IS NOT NULL THEN 1 ELSE 0 END AS SelectionPoint
	FROM INSERTED i
	LEFT JOIN DELETED d ON d.AuditItemID = i.AuditItemID 
END