CREATE TABLE [ParallelRun].[CaseDetails](
	[CaseID] [int] NOT NULL,
	[CreationDate] [datetime2](7) NOT NULL,
	[CaseStatusTypeID] [tinyint] NOT NULL,
	[CaseRejection] [int] NOT NULL,
	[Questionnaire] [varchar](255) NOT NULL,
	[QuestionnaireRequirementID] [int] NOT NULL,
	[QuestionnaireVersion] [tinyint] NULL,
	[SelectionTypeID] [smallint] NULL,
	[Selection] [varchar](255) NOT NULL,
	[ModelDerivative] [varchar](255) NOT NULL,
	[Title] [nvarchar](200) NULL,
	[FirstName] [nvarchar](100) NULL,
	[Initials] [nvarchar](100) NULL,
	[MiddleName] [nvarchar](100) NULL,
	[LastName] [nvarchar](100) NULL,
	[SecondLastName] [nvarchar](100) NULL,
	[GenderID] [int] NULL,
	[LanguageID] [int] NULL,
	[OrganisationName] [nvarchar](510) NULL,
	[OrganisationPartyID] [int] NULL,
	[PostalAddressContactMechanismID] [int] NULL,
	[EmailAddressContactMechanismID] [int] NULL,
	[CountryID] [smallint] NULL,
	[Country] [varchar](200) NULL,
	[CountryISOAlpha3] [char](3) NULL,
	[CountryISOAlpha2] [char](2) NULL,
	[EventTypeID] [smallint] NOT NULL,
	[EventType] [nvarchar](200) NOT NULL,
	[EventDate] [datetime2](7) NULL,
	[PartyID] [int] NULL,
	[VehicleRoleTypeID] [smallint] NULL,
	[VehicleID] [bigint] NULL,
	[EventID] [bigint] NULL,
	[OwnershipCycle] [tinyint] NULL,
	[SelectionRequirementID] [int] NOT NULL,
	[ModelRequirementID] [int] NOT NULL,
	[RegistrationNumber] [nvarchar](100) NULL,
	[RegistrationDate] [datetime2](7) NULL,
	[ModelDescription] [varchar](20) NOT NULL,
	[VIN] [nvarchar](50) NOT NULL,
	[VinPrefix] [nvarchar](30) NULL,
	[ChassisNumber] [nvarchar](20) NULL,
	[ManufacturerPartyID] [int] NOT NULL,
	[DealerPartyID] [int] NULL,
	[DealerCode] [nvarchar](20) NULL,
	[DealerName] [nvarchar](150) NULL,
	[RoadsideNetworkPartyID] [int] NULL,
	[RoadsideNetworkCode] [varchar](50) NULL,
	[RoadsideNetworkName] [nvarchar](150) NULL,
	[SaleType] [varchar](1) NULL,
	[VariantID] [smallint] NULL,
	[ModelVariant] [varchar](50) NULL
) 