CREATE TABLE [ParallelRun].[Comparisons_Vehicle](
	[ComparisonLoadDate] [date] NULL,
	[FileName] [nvarchar](100) NULL,
	[PhysicalFileRow] [int] NOT NULL,
	[RemoteAuditID] [bigint] NOT NULL,
	[LocalAuditID] [bigint] NOT NULL,
	[RemoteAuditItemID] [bigint] NOT NULL,
	[LocalAuditItemID] [bigint] NOT NULL,
	[Mismatch_VehicleID] [int] NOT NULL,
	[Mismatch_ModelID] [int] NOT NULL,
	[Mismatch_VIN] [int] NOT NULL,
	[Mismatch_VehicleIdentificationNumberUsable] [int] NOT NULL,
	[Mismatch_VINPrefix] [int] NOT NULL,
	[Mismatch_ChassisNumber] [int] NOT NULL,
	[Mismatch_BuildDate] [int] NOT NULL,
	[Mismatch_BuildYear] [int] NOT NULL,
	[Mismatch_ThroughDate] [int] NOT NULL,
	[Mismatch_ModelVariantID] [int] NOT NULL,
	[Mismatch_SVOTypeID] [int] NOT NULL,
	[Mismatch_FOBCode] [int] NOT NULL,
	[Mismatch_RegistrationID] [int] NOT NULL,
	[Mismatch_RegistrationNumber] [int] NOT NULL,
	[Mismatch_RegistrationDate] [int] NOT NULL,
	[Mismatch_Reg_ThroughDate] [int] NOT NULL
)