CREATE TABLE [ParallelRun].[Comparisons_CustomerUpdate_PostalAddress](
	[PartyID] [int] NOT NULL,
	[CaseID] [int] NOT NULL,

	[RemoteAuditID] [bigint] NOT NULL,
	[LocalAuditID] [bigint] NOT NULL,
	[RemoteAuditItemID] [bigint] NOT NULL,
	[LocalAuditItemID] [bigint] NOT NULL,

	[Mismatch_Address1] INT NOT NULL,
	[Mismatch_Address2] INT NOT NULL,
	[Mismatch_Address3] INT NOT NULL,
	[Mismatch_Address4] INT NOT NULL,
	[Mismatch_Address5] INT NOT NULL,
	[Mismatch_Address6] INT NOT NULL,
	[Mismatch_Address7] INT NOT NULL,
	[Mismatch_BuildingName] INT NOT NULL,
	[Mismatch_SubStreetNumber] INT NOT NULL,
	[Mismatch_SubStreet] INT NOT NULL,
	[Mismatch_SubStreetAndNumber] INT NOT NULL,
	[Mismatch_StreetNumber] INT NOT NULL,
	[Mismatch_Street] INT NOT NULL,
	[Mismatch_StreetAndNumber] INT NOT NULL,
	[Mismatch_SubLocality] INT NOT NULL,
	[Mismatch_Locality] INT NOT NULL,
	[Mismatch_Town] INT NOT NULL,
	[Mismatch_Region] INT NOT NULL,
	[Mismatch_CountryID] INT NOT NULL,
	[Mismatch_PostCode] INT NOT NULL,
	[Mismatch_ContactMechanismID] INT NOT NULL,
	[Mismatch_CasePartyCombinationValid] INT NOT NULL,
	[Mismatch_ParentAuditItemID] INT NOT NULL,
	[Mismatch_DateProcessed] INT NOT NULL
)