CREATE TABLE [ParallelRun].[CustomerUpdate_PostalAddress](
	[PartyID] [int] NOT NULL,
	[CaseID] [int] NOT NULL,
	[Address1] [nvarchar](400) NULL,
	[Address2] [nvarchar](400) NULL,
	[Address3] [nvarchar](400) NULL,
	[Address4] [nvarchar](400) NULL,
	[Address5] [nvarchar](400) NULL,
	[Address6] [nvarchar](400) NULL,
	[Address7] [nvarchar](400) NULL,
	[BuildingName] [nvarchar](400) NULL,
	[SubStreetNumber] [nvarchar](40) NULL,
	[SubStreet] [nvarchar](400) NULL,
	[SubStreetAndNumber] [nvarchar](400) NULL,
	[StreetNumber] [nvarchar](40) NULL,
	[Street] [nvarchar](400) NULL,
	[StreetAndNumber] [nvarchar](400) NULL,
	[SubLocality] [nvarchar](400) NULL,
	[Locality] [nvarchar](400) NULL,
	[Town] [nvarchar](400) NULL,
	[Region] [nvarchar](400) NULL,
	[CountryID] [smallint] NULL,
	[PostCode] [nvarchar](60) NULL,
	[ContactMechanismID] [int] NULL,
	[AuditID] [bigint] NOT NULL,
	[AuditItemID] [bigint] NOT NULL,
	[CasePartyCombinationValid] [bit] NOT NULL,
	[ParentAuditItemID] [bigint] NULL,
	[DateProcessed] [datetime2](7) NOT NULL
)