CREATE TABLE [ParallelRun].[MismatchVehicles](
	[ComparisonLoadDate] [nvarchar](255) NULL,
	[Filename] [nvarchar](255) NULL,
	[PhysicalFileRow] [nvarchar](255) NULL,
	[Mismatch_VehicleID] [nvarchar](255) NULL,
	[GfK VehicleID] [nvarchar](255) NULL,
	[IPSOS VehicleID] [nvarchar](255) NULL,
	[Mismatch_ModelID] [nvarchar](255) NULL,
	[GfK ModelID] [nvarchar](255) NULL,
	[IPSOS ModelID] [nvarchar](255) NULL,
	[Mismatch_VIN] [nvarchar](255) NULL,
	[GfK VIN] [nvarchar](255) NULL,
	[IPSOS VIN] [nvarchar](255) NULL,
	[Mismatch_VehicleIdentificationNumberUsable] [nvarchar](255) NULL,
	[GfK VehicleIdentificationNumberUsable] [nvarchar](255) NULL,
	[IPSOS VehicleIdentificationNumberUsable] [nvarchar](255) NULL,
	[Mismatch_VINPrefix] [nvarchar](255) NULL,
	[GfK VINPrefix] [nvarchar](255) NULL,
	[IPSOS VINPrefix] [nvarchar](255) NULL,
	[Mismatch_ChassisNumber] [nvarchar](255) NULL,
	[GfK ChassisNumber] [nvarchar](255) NULL,
	[IPSOS ChassisNumber] [nvarchar](255) NULL,
	[Mismatch_BuildDate] [nvarchar](255) NULL,
	[GfK BuildDate] [nvarchar](255) NULL,
	[IPSOS BuildDate] [nvarchar](255) NULL,
	[Mismatch_BuildYear] [nvarchar](255) NULL,
	[GfK BuildYear] [nvarchar](255) NULL,
	[IPSOS BuildYear] [nvarchar](255) NULL,
	[Mismatch_ThroughDate] [nvarchar](255) NULL,
	[GfK ThroughDate] [nvarchar](255) NULL,
	[IPSOS ThroughDate] [nvarchar](255) NULL,
	[Mismatch_ModelVariantID] [nvarchar](255) NULL,
	[GfK ModelVariantID] [nvarchar](255) NULL,
	[IPSOS ModelVariantID] [nvarchar](255) NULL,
	[Mismatch_SVOTypeID] [nvarchar](255) NULL,
	[GfK SVOTypeID] [nvarchar](255) NULL,
	[IPSOS SVOTypeID] [nvarchar](255) NULL,
	[Mismatch_FOBCode] [nvarchar](255) NULL,
	[GfK FOBCode] [nvarchar](255) NULL,
	[IPSOS FOBCode] [nvarchar](255) NULL
) ON [PRIMARY]