CREATE TABLE [ParallelRun].[MismatchPostalAddresses](
	[ComparisonLoadDate] [datetime] NULL,
	[Filename] [nvarchar](255) NULL,
	[PhysicalFileRow] [float] NULL,
	[Mismatch_ContactMechanismID] [float] NULL,
	[GfK ContactMechanismID] [float] NULL,
	[IPSOS ContactMechanismID] [float] NULL,
	[MatchedODSAddressIDNew] [float] NULL,
	[Mismatch_BuildingName] [float] NULL,
	[GfK BuildingName] [nvarchar](255) NULL,
	[IPSOS BuildingName] [nvarchar](255) NULL,
	[Mismatch_SubStreetNumber] [float] NULL,
	[GfK SubStreetNumber] [nvarchar](255) NULL,
	[IPSOS SubStreetNumber] [nvarchar](255) NULL,
	[Mismatch_SubStreet] [float] NULL,
	[GfK SubStreet] [nvarchar](255) NULL,
	[IPSOS SubStreet] [nvarchar](255) NULL,
	[Mismatch_StreetNumber] [float] NULL,
	[GfK StreetNumber] [nvarchar](255) NULL,
	[IPSOS StreetNumber] [nvarchar](255) NULL,
	[Mismatch_Street] [float] NULL,
	[GfK Street] [nvarchar](255) NULL,
	[IPSOS Street] [nvarchar](255) NULL,
	[Mismatch_SubLocality] [float] NULL,
	[GfK SubLocality] [nvarchar](255) NULL,
	[IPSOS SubLocality] [nvarchar](255) NULL,
	[Mismatch_Locality] [float] NULL,
	[GfK Locality] [nvarchar](255) NULL,
	[IPSOS Locality] [nvarchar](255) NULL,
	[Mismatch_Town] [float] NULL,
	[GfK Town] [nvarchar](255) NULL,
	[IPSOS Town] [nvarchar](255) NULL,
	[Mismatch_Region] [float] NULL,
	[GfK Region] [nvarchar](255) NULL,
	[IPSOS Region] [nvarchar](255) NULL,
	[Mismatch_PostCode] [float] NULL,
	[GfK PostCode] [nvarchar](255) NULL,
	[IPSOS PostCode] [nvarchar](255) NULL,
	[Mismatch_CountryID] [float] NULL,
	[GfK CountryID] [float] NULL,
	[IPSOS CountryID] [float] NULL,
	[Mismatch_AddressChecksum] [float] NULL,
	[GfK AddressChecksum] [float] NULL,
	[IPSOS AddressChecksum] [float] NULL
) ON [PRIMARY]
