CREATE TABLE [ParallelRun].[MismatchTelephoneNumbers](
	[ComparisonLoadDate] [datetime] NULL,
	[Filename] [nvarchar](255) NULL,
	[PhysicalFileRow] [nvarchar](255) NULL,
	[Mismatch_tn_ContactNumber] [nvarchar](255) NULL,
	[GfK tn_ContactNumber] [nvarchar](255) NULL,
	[IPSOS tn_ContactNumber] [nvarchar](255) NULL,
	[Mismatch_tn_ContactNumberChecksum] [nvarchar](255) NULL,
	[GfK tn_ContactNumberChecksum] [nvarchar](255) NULL,
	[IPSOS tn_ContactNumberChecksum] [nvarchar](255) NULL,
	[Mismatch_ptn_ContactNumber] [nvarchar](255) NULL,
	[GfK ptn_ContactNumber] [nvarchar](255) NULL,
	[IPSOS ptn_ContactNumber] [nvarchar](255) NULL,
	[Mismatch_ptn_ContactNumberChecksum] [nvarchar](255) NULL,
	[GfK ptn_ContactNumberChecksum] [nvarchar](255) NULL,
	[IPSOS ptn_ContactNumberChecksum] [nvarchar](255) NULL,
	[Mismatch_btn_ContactNumber] [nvarchar](255) NULL,
	[GfK btn_ContactNumber] [nvarchar](255) NULL,
	[IPSOS btn_ContactNumber] [nvarchar](255) NULL,
	[Mismatch_btn_ContactNumberChecksum] [nvarchar](255) NULL,
	[GfK btn_ContactNumberChecksum] [nvarchar](255) NULL,
	[IPSOS btn_ContactNumberChecksum] [nvarchar](255) NULL,
	[Mismatch_mtn_ContactNumber] [nvarchar](255) NULL,
	[GfK mtn_ContactNumber] [nvarchar](255) NULL,
	[IPSOS mtn_ContactNumber] [nvarchar](255) NULL,
	[Mismatch_mtn_ContactNumberChecksum] [nvarchar](255) NULL,
	[GfK mtn_ContactNumberChecksum] [nvarchar](255) NULL,
	[IPSOS mtn_ContactNumberChecksum] [nvarchar](255) NULL,
	[Mismatch_pmtn_ContactNumber] [nvarchar](255) NULL,
	[GfK pmtn_ContactNumber] [nvarchar](255) NULL,
	[IPSOS pmtn_ContactNumber] [nvarchar](255) NULL,
	[Mismatch_pmtn_ContactNumberChecksum] [nvarchar](255) NULL,
	[GfK pmtn_ContactNumberChecksum] [nvarchar](255) NULL,
	[IPSOS pmtn_ContactNumberChecksum] [nvarchar](255) NULL
) ON [PRIMARY]
