CREATE TABLE [ParallelRun].[MismatchChecking](
	[ComparisonLoadDate] [datetime] NULL,
	[FileName] [nvarchar](255) NULL,
	[PhysicalFileRow] [float] NULL,
	[Mismatched_CaseCreation] [float] NULL,
	[GfK CaseID] [nvarchar](255) NULL,
	[IPSOS CaseID] [float] NULL,
	[RemoteLoadedDate] [datetime] NULL,
	[LocalLoadedDate] [datetime] NULL,
	[Mismatch_LoadedDay] [float] NULL,
	[Mismatch_ManufacturerID] [float] NULL,
	[Mismatch_SampleSupplierPartyID] [float] NULL,
	[Mismatch_CountryID] [float] NULL,
	[Mismatch_MatchedODSPartyID] [float] NULL,
	[Mismatch_MatchedODSPersonID] [float] NULL,
	[GfK MatchedODSPersonID] [float] NULL,
	[IPSOS MatchedODSPersonID] [float] NULL,
	[MatchedODSPersonIDNew] [float] NULL,
	[GfK Name] [nvarchar](255) NULL,
	[IPSOS Name] [nvarchar](255) NULL,
	[Mismatch_MatchedODSOrganisationID] [float] NULL,
	[MatchedODSOrganisationIDNew] [float] NULL,
	[GfK MatchedODSOrganisationID] [float] NULL,
	[IPSOS MatchedODSOrganisationID] [float] NULL,
	[GfK MatchedOrganisationName] [nvarchar](255) NULL,
	[IPSOS MatchedOrganisationName] [nvarchar](255) NULL,
	[Mismatch_SelectionOrganisationID] [float] NULL,
	[SelectionOrganisationIDNew] [float] NULL,
	[GfK SelectionOrganisationID] [nvarchar](255) NULL,
	[IPSOS SelectionOrganisationID] [nvarchar](255) NULL,
	[GfK SelectedOrganisationName] [nvarchar](255) NULL,
	[IPSOS SelectedOrganisationName] [nvarchar](255) NULL,
	[Mismatch_MatchedODSAddressID] [float] NULL,
	[MatchedODSAddressIDNew] [float] NULL,
	[GfK MatchedODSAddressID] [float] NULL,
	[IPSOS MatchedODSAddressID] [float] NULL,
	[GfK Address] [nvarchar](255) NULL,
	[IPSOS Address] [nvarchar](255) NULL,
	[Mismatch_AddressChecksum] [float] NULL,
	[Mismatch_SelectionPostalID] [float] NULL,
	[SelectionPostalIDNew] [float] NULL,
	[Mismatch_MatchedODSEmailAddressID] [float] NULL,
	[MatchedODSEmailAddressIDNew] [float] NULL,
	[GfK MatchedODSEmailAddressID] [float] NULL,
	[IPSOS MatchedODSEmailAddressID] [float] NULL,
	[GfK EmailAddress] [nvarchar](255) NULL,
	[IPSOS EmailAddress] [nvarchar](255) NULL,
	[Mismatch_MatchedODSPrivEmailAddressID] [float] NULL,
	[Mismatch_SelectionEmailID] [float] NULL,
	[SelectionEmailIDNew] [float] NULL,
	[GfK SelectionEmailID] [nvarchar](255) NULL,
	[IPSOS SelectionEmailID] [float] NULL,
	[GfK SelectionEmailAddress] [nvarchar](255) NULL,
	[IPSOS SelectionEmailAddress] [nvarchar](255) NULL,
	[Mismatch_MatchedODSTelID] [float] NULL,
	[MatchedODSTelIDNew] [float] NULL,
	[Mismatch_MatchedODSPrivTelID] [float] NULL,
	[MatchedODSPrivTelIDNew] [float] NULL,
	[Mismatch_MatchedODSBusTelID] [float] NULL,
	[MatchedODSBusTelIDNew] [float] NULL,
	[Mismatch_SelectionPhoneID] [float] NULL,
	[SelectionPhoneIDNew] [float] NULL,
	[Mismatch_SelectionLandlineID] [float] NULL,
	[SelectionLandlineIDNew] [float] NULL,
	[Mismatch_MatchedODSMobileTelID] [float] NULL,
	[MatchedODSMobileTelIDNew] [float] NULL,
	[Mismatch_MatchedODSPrivMobileTelID] [float] NULL,
	[Mismatch_SelectionMobileID] [float] NULL,
	[SelectionMobileIDNew] [float] NULL,
	[Mismatch_PartySuppression] [float] NULL,
	[Mismatch_PhoneSuppression] [float] NULL,
	[Mismatch_PostalSuppression] [float] NULL,
	[Mismatch_EmailSuppression] [float] NULL,
	[Mismatch_MatchedODSVehicleID] [float] NULL,
	[MatchedODSVehicleIDNew] [float] NULL,
	[GfK VIN] [nvarchar](255) NULL,
	[IPSOS VIN] [nvarchar](255) NULL,
	[Mismatch_ODSRegistrationID] [float] NULL,
	[Mismatch_MatchedODSModelID] [float] NULL,
	[Mismatch_OwnershipCycle] [float] NULL,
	[Mismatch_MatchedODSEventID] [float] NULL,
	[MatchedODSEventIDNew] [float] NULL,
	[Mismatch_ODSEventTypeID] [float] NULL,
	[Mismatch_SaleDate] [float] NULL,
	[Mismatch_ServiceDate] [float] NULL,
	[Mismatch_SalesDealerCode] [float] NULL,
	[Mismatch_SalesDealerID] [float] NULL,
	[GfK SalesDealerID] [float] NULL,
	[IPSOS SalesDealerID] [float] NULL,
	[Mismatch_ServiceDealerCode] [float] NULL,
	[Mismatch_ServiceDealerID] [float] NULL,
	[GfK ServiceDealerID] [float] NULL,
	[IPSOS ServiceDealerID] [float] NULL,
	[Mismatch_RoadsideNetworkCode] [float] NULL,
	[Mismatch_RoadsideNetworkPartyID] [float] NULL,
	[Mismatch_RoadsideDate] [float] NULL,
	[Mismatch_CRCCentreCode] [float] NULL,
	[Mismatch_CRCCentrePartyID] [float] NULL,
	[Mismatch_CRCDate] [float] NULL,
	[Mismatch_LostLeadDate] [float] NULL,
	[Mismatch_Brand] [float] NULL,
	[Mismatch_Market] [float] NULL,
	[Mismatch_Questionnaire] [float] NULL,
	[Mismatch_QuestionnaireRequirementID] [float] NULL,
	[Mismatch_SampleRowProcessed] [float] NULL,
	[Mismatch_SampleRowProcessedDate] [float] NULL,
	[Mismatch_StartDays] [float] NULL,
	[Mismatch_EndDays] [float] NULL,
	[Mismatch_SuppliedName] [float] NULL,
	[Mismatch_SuppliedAddress] [float] NULL,
	[Mismatch_SuppliedPhoneNumber] [float] NULL,
	[Mismatch_SuppliedMobilePhone] [float] NULL,
	[Mismatch_SuppliedEmail] [float] NULL,
	[Mismatch_SuppliedRegistration] [float] NULL,
	[Mismatch_SuppliedEventDate] [float] NULL,
	[Mismatch_EventDateOutOfDate] [float] NULL,
	[Mismatch_EventNonSolicitation] [float] NULL,
	[Mismatch_PartyNonSolicitation] [float] NULL,
	[Mismatch_UnmatchedModel] [float] NULL,
	[Mismatch_UncodedDealer] [float] NULL,
	[Mismatch_EventAlreadySelected] [float] NULL,
	[Mismatch_NonLatestEvent] [float] NULL,
	[Mismatch_InvalidOwnershipCycle] [float] NULL,
	[Mismatch_RecontactPeriod] [float] NULL,
	[Mismatch_InvalidVehicleRole] [float] NULL,
	[Mismatch_ExclusionListMatch] [float] NULL,
	[Mismatch_InvalidEmailAddress] [float] NULL,
	[Mismatch_BarredEmailAddress] [float] NULL,
	[Mismatch_BarredDomain] [float] NULL,
	[Mismatch_WrongEventType] [float] NULL,
	[Mismatch_MissingStreet] [float] NULL,
	[Mismatch_MissingPostcode] [float] NULL,
	[Mismatch_MissingEmail] [float] NULL,
	[Mismatch_MissingTelephone] [float] NULL,
	[Mismatch_MissingStreetAndEmail] [float] NULL,
	[Mismatch_MissingTelephoneAndEmail] [float] NULL,
	[Mismatch_InvalidModel] [float] NULL,
	[Mismatch_InvalidVariant] [float] NULL,
	[Mismatch_MissingMobilePhone] [float] NULL,
	[Mismatch_MissingMobilePhoneAndEmail] [float] NULL,
	[Mismatch_MissingPartyName] [float] NULL,
	[Mismatch_MissingLanguage] [float] NULL,
	[Mismatch_CaseIDPrevious] [float] NULL,
	[Mismatch_RelativeRecontactPeriod] [float] NULL,
	[Mismatch_InvalidManufacturer] [float] NULL,
	[Mismatch_InternalDealer] [float] NULL,
	[Mismatch_EventDateTooYoung] [float] NULL,
	[Mismatch_InvalidRoleType] [float] NULL,
	[Mismatch_InvalidSaleType] [float] NULL,
	[Mismatch_InvalidAFRLCode] [float] NULL,
	[Mismatch_SuppliedAFRLCode] [float] NULL,
	[Mismatch_DealerExclusionListMatch] [float] NULL,
	[Mismatch_ContactPreferencesSuppression] [float] NULL,
	[Mismatch_ContactPreferencesPartySuppress] [float] NULL,
	[Mismatch_ContactPreferencesEmailSuppress] [float] NULL,
	[Mismatch_ContactPreferencesPhoneSuppress] [float] NULL,
	[Mismatch_ContactPreferencesPostalSuppress] [float] NULL,
	[Mismatch_ContactPreferencesUnsubscribed] [float] NULL,
	[Mismatch_InvalidCRMSaleType] [float] NULL,
	[Mismatch_MissingLostLeadAgency] [float] NULL,
	[Mismatch_InvalidDateOfLastContact] [float] NULL
) ON [PRIMARY]
