CREATE TABLE [ParallelRun].[MismatchPeople](
	[ComparisonLoadDate] [datetime] NULL,
	[Filename] [nvarchar](255) NULL,
	[PhysicalFileRow] [float] NULL,
	[GfK MatchedODSPersonID] [float] NULL,
	[IPSOS MatchedODSPersonID] [float] NULL,
	[Mismatch_FromDate] [float] NULL,
	[GfK FromDate] [datetime] NULL,
	[IPSOS FromDate] [datetime] NULL,
	[Mismatch_TitleID] [float] NULL,
	[GfK TitleID] [float] NULL,
	[GfK Title] [nvarchar](255) NULL,
	[IPSOS TitleID] [float] NULL,
	[IPSOS Title] [nvarchar](255) NULL,
	[Mismatch_Initials] [float] NULL,
	[GfK Initials] [nvarchar](255) NULL,
	[IPSOS Initials] [nvarchar](255) NULL,
	[Mismatch_FirstName] [float] NULL,
	[GfK FirstName] [nvarchar](255) NULL,
	[IPSOS FirstName] [nvarchar](255) NULL,
	[Mismatch_MiddleName] [float] NULL,
	[GfK MiddleName] [nvarchar](255) NULL,
	[IPSOS MiddleName] [nvarchar](255) NULL,
	[Mismatch_LastName] [float] NULL,
	[GfK LastName] [nvarchar](255) NULL,
	[IPSOS LastName] [nvarchar](255) NULL,
	[Mismatch_SecondLastName] [float] NULL,
	[GfK SecondLastName] [nvarchar](255) NULL,
	[IPSOS SecondLastName] [nvarchar](255) NULL,
	[Mismatch_GenderID] [float] NULL,
	[GfK GenderID] [float] NULL,
	[IPSOS GenderID] [float] NULL,
	[Mismatch_BirthDate] [float] NULL,
	[GfK BirthDate] DATE NULL,
	[IPSOS BirthDate] DATE NULL,
	[Mismatch_MonthAndYearOfBirth] [float] NULL,
	[GfK MonthAndYearOfBirth] [datetime] NULL,
	[IPSOS MonthAndYearOfBirth] [datetime] NULL,
	[Mismatch_PreferredMethodOfContact] [float] NULL,
	[GfK PreferredMethodOfContact] [nvarchar](255) NULL,
	[IPSOS PreferredMethodOfContact] [nvarchar](255) NULL,
	[Mismatch_NameChecksum] [float] NULL,
	[GfK NameChecksum] [float] NULL,
	[IPSOS NameChecksum] [float] NULL
) ON [PRIMARY]