CREATE TABLE [ParallelRun].[SampleQualityAndSelectionLogging] (
	[FileName] [varchar](100) NOT NULL,
	[LoadedDate] [datetime2](7) NOT NULL,
	[AuditID] [bigint] NOT NULL,
	[AuditItemID] [bigint] NOT NULL,
	[PhysicalFileRow] [int] NOT NULL,
	[ManufacturerID] [int] NULL,
	[SampleSupplierPartyID] [int] NULL,
	[MatchedODSPartyID] [int] NOT NULL,
	[PersonParentAuditItemID] [bigint] NULL,
	[MatchedODSPersonID] [int] NOT NULL,
	[LanguageID] [smallint] NOT NULL,
	[PartySuppression] [bit] NOT NULL,
	[OrganisationParentAuditItemID] [bigint] NULL,
	[MatchedODSOrganisationID] [int] NOT NULL,
	[AddressParentAuditItemID] [bigint] NULL,
	[MatchedODSAddressID] [int] NOT NULL,
	[CountryID] [smallint] NULL,
	[PostalSuppression] [bit] NOT NULL,
	[AddressChecksum] [bigint] NULL,
	[MatchedODSTelID] [int] NULL,
	[MatchedODSPrivTelID] [int] NULL,
	[MatchedODSBusTelID] [int] NULL,
	[MatchedODSMobileTelID] [int] NULL,
	[MatchedODSPrivMobileTelID] [int] NULL,
	[MatchedODSEmailAddressID] [int] NULL,
	[MatchedODSPrivEmailAddressID] [int] NULL,
	[EmailSuppression] [bit] NOT NULL,
	[VehicleParentAuditItemID] [bigint] NULL,
	[MatchedODSVehicleID] [bigint] NOT NULL,
	[ODSRegistrationID] [int] NULL,
	[MatchedODSModelID] [smallint] NULL,
	[OwnershipCycle] [tinyint] NULL,
	[MatchedODSEventID] [bigint] NOT NULL,
	[ODSEventTypeID] [smallint] NULL,
	[SaleDateOrig] [varchar](20) NULL,
	[SaleDate] [datetime2](7) NULL,
	[ServiceDateOrig] [varchar](20) NULL,
	[ServiceDate] [datetime2](7) NULL,
	[InvoiceDateOrig] [varchar](20) NULL,
	[InvoiceDate] [datetime2](7) NULL,
	[WarrantyID] [int] NULL,
	[SalesDealerCodeOriginatorPartyID] [int] NULL,
	[SalesDealerCode] [nvarchar](10) NULL,
	[SalesDealerID] [int] NOT NULL,
	[ServiceDealerCodeOriginatorPartyID] [int] NULL,
	[ServiceDealerCode] [nvarchar](10) NULL,
	[ServiceDealerID] [int] NOT NULL,
	[RoadsideNetworkOriginatorPartyID] [int] NULL,
	[RoadsideNetworkCode] [nvarchar](50) NULL,
	[RoadsideNetworkPartyID] [int] NOT NULL,
	[RoadsideDate] [datetime2](7) NULL,
	[CRCCentreOriginatorPartyID] [int] NULL,
	[CRCCentreCode] [nvarchar](50) NULL,
	[CRCCentrePartyID] [int] NOT NULL,
	[CRCDate] [datetime2](7) NULL,
	[Brand] [nvarchar](510) NULL,
	[Market] [varchar](200) NULL,
	[Questionnaire] [varchar](255) NULL,
	[QuestionnaireRequirementID] [int] NULL,
	[StartDays] [int] NULL,
	[EndDays] [int] NULL,
	[SuppliedName] [bit] NOT NULL,
	[SuppliedAddress] [bit] NOT NULL,
	[SuppliedPhoneNumber] [bit] NOT NULL,
	[SuppliedMobilePhone] [bit] NOT NULL,
	[SuppliedEmail] [bit] NOT NULL,
	[SuppliedVehicle] [bit] NOT NULL,
	[SuppliedRegistration] [bit] NOT NULL,
	[SuppliedEventDate] [bit] NOT NULL,
	[EventDateOutOfDate] [bit] NOT NULL,
	[EventNonSolicitation] [bit] NOT NULL,
	[PartyNonSolicitation] [bit] NOT NULL,
	[UnmatchedModel] [bit] NOT NULL,
	[UncodedDealer] [bit] NOT NULL,
	[EventAlreadySelected] [bit] NOT NULL,
	[NonLatestEvent] [bit] NOT NULL,
	[InvalidOwnershipCycle] [bit] NOT NULL,
	[RecontactPeriod] [bit] NOT NULL,
	[InvalidVehicleRole] [bit] NOT NULL,
	[CrossBorderAddress] [bit] NOT NULL,
	[CrossBorderDealer] [bit] NOT NULL,
	[ExclusionListMatch] [bit] NOT NULL,
	[InvalidEmailAddress] [bit] NOT NULL,
	[BarredEmailAddress] [bit] NOT NULL,
	[BarredDomain] [bit] NOT NULL,
	[CaseID] [varchar](11) NULL,
	[SampleRowProcessed] [bit] NOT NULL,
	[SampleRowProcessedDate] [datetime2](7) NULL,
	[WrongEventType] [bit] NOT NULL,
	[MissingStreet] [bit] NOT NULL,
	[MissingPostcode] [bit] NOT NULL,
	[MissingEmail] [bit] NOT NULL,
	[MissingTelephone] [bit] NOT NULL,
	[MissingStreetAndEmail] [bit] NOT NULL,
	[MissingTelephoneAndEmail] [bit] NOT NULL,
	[InvalidModel] [bit] NOT NULL,
	[InvalidVariant] [bit] NOT NULL,
	[MissingMobilePhone] [bit] NOT NULL,
	[MissingMobilePhoneAndEmail] [bit] NOT NULL,
	[MissingPartyName] [bit] NOT NULL,
	[MissingLanguage] [bit] NOT NULL,
	[CaseIDPrevious] [int] NULL,
	[RelativeRecontactPeriod] [int] NOT NULL,
	[InvalidManufacturer] [bit] NOT NULL,
	[InternalDealer] [bit] NOT NULL,
	[EventDateTooYoung] [bit] NOT NULL,
	[InvalidRoleType] [bit] NOT NULL,
	[InvalidSaleType] [bit] NOT NULL,
	[InvalidAFRLCode] [bit] NOT NULL,
	[SuppliedAFRLCode] [varchar](10) NULL,
	[DealerExclusionListMatch] [bit] NOT NULL,
	[PhoneSuppression] [bit] NULL,
	[LostLeadDate] [datetime2](7) NULL,
	[ContactPreferencesSuppression] [bit] NULL,
	[NotInQuota] [bit] NULL,
	[ContactPreferencesPartySuppress] [bit] NULL,
	[ContactPreferencesEmailSuppress] [bit] NULL,
	[ContactPreferencesPhoneSuppress] [bit] NULL,
	[ContactPreferencesPostalSuppress] [bit] NULL,
	[DealerPilotOutputFiltered] [bit] NULL,
	[InvalidCRMSaleType] [bit] NOT NULL,
	[MissingLostLeadAgency] [bit] NULL,
	[PDIFlagSet] [bit] NULL,
	[BodyshopEventDateOrig] [varchar](20) NULL,
	[BodyshopEventDate] [datetime2](7) NULL,
	[BodyshopDealerCode] [nvarchar](10) NULL,
	[BodyshopDealerID] [int] NULL,
	[BodyshopDealerCodeOriginatorPartyID] [int] NULL,
	[ContactPreferencesUnsubscribed] [bit] NULL,
	[SelectionOrganisationID] [int] NULL,
	[SelectionPostalID] [int] NULL,
	[SelectionEmailID] [int] NULL,
	[SelectionPhoneID] [int] NULL,
	[SelectionLandlineID] [int] NULL,
	[SelectionMobileID] [int] NULL,
	[NonSelectableWarrantyEvent] [bit] NOT NULL,
	[IAssistanceCentreOriginatorPartyID] [int] NULL,
	[IAssistanceCentreCode] [nvarchar](50) NULL,
	[IAssistanceCentrePartyID] [int] NOT NULL,
	[IAssistanceDate] [datetime2](7) NULL,
	[InvalidDateOfLastContact] [bit] NOT NULL
);
