ALTER TABLE [DealerManagement].[DEALERS_JLRCSP_UPDATE_OutletCode]
    ADD CONSTRAINT [PK_DEALERS_JLRCSP_DealerCodeChangeOverwrites] PRIMARY KEY CLUSTERED ([IP_OutletCodeChangeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

