ALTER TABLE [DealerManagement].[DEALERS_JLRCSP_UPDATE_TransferDealer]
    ADD CONSTRAINT [PK_DEALERS_JLRCSP_UPDATE_TransferDealer] PRIMARY KEY CLUSTERED ([IP_TransferDealerChangeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

