CREATE NONCLUSTERED INDEX [IX_Base_DuplicateRowFlag] ON [SampleReport].[Base] 
(
	[DuplicateRowFlag] ASC
)
INCLUDE ( [SentDate],
[FileName],
[AuditItemID],
[CaseID],
[VIN],
[EventDate]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 88) ON [PRIMARY]
GO

