CREATE NONCLUSTERED INDEX [IX_Base_Vin_EventDate] ON [SampleReport].[Base] 
(
	[VIN] ASC,
	[EventDate] ASC
)
INCLUDE ( [SentDate],
[DuplicateRowFlag],
[FileName],
[AuditItemID],
[CaseID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO


