CREATE NONCLUSTERED INDEX [IX_YearlyEchoHistory_AuditItemID_CheckSumCalc] ON [SampleReport].[YearlyEchoHistory] 
(
	[AuditItemID] ASC,
	[CheckSumCalc] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 88) ON [PRIMARY]
GO



