CREATE TABLE [DealerManagement].[DEALERS_JLRCSP_Flat] (
    [Manufacturer]            NVARCHAR (255)  NOT NULL,
    [SuperNationalRegion]     NVARCHAR (255)  NULL,
    [BusinessRegion]		  NVARCHAR (255)  NULL,
    [Market]                  NVARCHAR (255)  NOT NULL,
    [SubNationalTerritory]    NVARCHAR (255)  NULL,
    [SubNationalRegion]       NVARCHAR (255)  NULL,
    [DealerGroup]             NVARCHAR (255)  NULL,
    [DealerName]              NVARCHAR (255)  NULL,
    [DealerCode]              NVARCHAR (210)   NULL,
    [ManufacturerDealerCode]  NVARCHAR (210)   NULL,
    [OutletPartyID]           INT             NULL,
    [OutletFunction]          NVARCHAR (25)   NULL,
    [OutletFunctionID]        SMALLINT        NULL,
    [FromDate]                DATETIME        NULL,
    [ThroughDate]             DATETIME        NULL,
    [TransferDealerName]      NVARCHAR (255)  NULL,
    [TransferDealerCode]      NVARCHAR (210)   NULL,
    [TransferPartyID]         INT             NULL,
    [DealerCodes]             NVARCHAR (1000) NULL,
    [ManufacturerDealerCodes] NVARCHAR (1000) NULL,
    [Town]                    NVARCHAR (100)  NULL,
    [OutletCode_GDD]          NVARCHAR (210)  NULL,
    [PAGCode]				  NVARCHAR (210)  NULL,
    [PAGName]				  NVARCHAR (210)  NULL,
    [SVODealer]				  BIT			  NOT NULL,
    [FleetDealer]             BIT			  NOT NULL,
	[Dealer10DigitCode]		  NVARCHAR (210)  NULL
);

