CREATE TABLE [WeeklySampleCheck].[SevenDayResultCountBMQ](
	[Market] [nvarchar](255) NULL,
	[Brand] [nvarchar](255) NULL,
	[Questionnaire] [nvarchar](255) NULL,
	[Frequency] [nvarchar](255) NULL,
	[File_Count] [int] NULL,
	[FileRow_Count] [bigint] NULL,
	[FileRow_LoadedCount] [int] NULL,
	[Selected_Count] [int] NULL,
	[ResultDay] [datetime] NULL
) ON [PRIMARY]