CREATE TABLE [WeeklySampleCheck].[SevenDayResultCountBMQbyDay](
	[Brand] [nvarchar](255) NULL,
	[Market] [nvarchar](255) NULL,
	[Questionnaire] [nvarchar](255) NULL,
	[Frequency] [nvarchar](255) NULL,
	[File_Count - Thursday] [int] NULL,
	[FileRow_Count - Thursday] [bigint] NULL,
	[FileRow_LoadedCount - Thursday] [int] NULL,
	[Selected_Count - Thursday] [int] NULL,
	[File_Count - Wednesday] [int] NULL,
	[FileRow_Count - Wednesday] [bigint] NULL,
	[FileRow_LoadedCount - Wednesday] [int] NULL,
	[Selected_Count - Wednesday] [int] NULL,
	[File_Count - Tuesday] [int] NULL,
	[FileRow_Count - Tuesday] [bigint] NULL,
	[FileRow_LoadedCount - Tuesday] [int] NULL,
	[Selected_Count - Tuesday] [int] NULL,
	[File_Count - Monday] [int] NULL,
	[FileRow_Count - Monday] [bigint] NULL,
	[FileRow_LoadedCount - Monday] [int] NULL,
	[Selected_Count - Monday] [int] NULL,
	[File_Count - Sunday] [int] NULL,
	[FileRow_Count - Sunday] [bigint] NULL,
	[FileRow_LoadedCount - Sunday] [int] NULL,
	[Selected_Count - Sunday] [int] NULL,
	[File_Count - Saturday] [int] NULL,
	[FileRow_Count - Saturday] [bigint] NULL,
	[FileRow_LoadedCount - Saturday] [int] NULL,
	[Selected_Count - Saturday] [int] NULL,
	[File_Count - Friday] [int] NULL,
	[FileRow_Count - Friday] [bigint] NULL,
	[FileRow_LoadedCount - Friday] [int] NULL,
	[Selected_Count - Friday] [int] NULL
) ON [PRIMARY]