ALTER TABLE [dbo].[FileTypes]
    ADD CONSTRAINT [PK_FileTypes] PRIMARY KEY CLUSTERED ([FileTypeID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

