ALTER TABLE [dbo].[FileRowsRemovedBeforeLoad]
    ADD CONSTRAINT [PK_FileRowsRemovedBeforeLoad] PRIMARY KEY CLUSTERED (AuditID ASC, [PhysicalRow] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

