
/*  -- No longer used -- Now files are loaded into Canada.Service table -- See BUG 13690


CREATE TABLE [Stage].[Canada_Service]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AuditID] [dbo].[AuditID] NULL,
	[PhysicalRowID] [int] NULL,

	[DEALER_ID]     [dbo].[LoadText] NULL,
	[RO_NUM]     [dbo].[LoadText] NULL,
	[RO_CLOSE_DATE]     [dbo].[LoadText] NULL,
	[RO_OPEN_DATE]     [dbo].[LoadText] NULL,
	[CUST_CONTACT_ID]     [dbo].[LoadText] NULL,
	[CUST_FIRST_NAME]     [dbo].[LoadText] NULL,
	[CUST_MIDDLE_NAME]     [dbo].[LoadText] NULL,
	[CUST_LAST_NAME]     [dbo].[LoadText] NULL,
	[CUST_SALUTATION]     [dbo].[LoadText] NULL,
	[CUST_SUFFIX]     [dbo].[LoadText] NULL,
	[CUST_FULL_NAME]     [dbo].[LoadText] NULL,
	[CUST_TITLE]     [dbo].[LoadText] NULL,
	[CUST_BUSINESS_PERSON_FLAG]     [dbo].[LoadText] NULL,
	[CUST_COMPANY_NAME]     [dbo].[LoadText] NULL,
	[CUST_DEPARTMENT]     [dbo].[LoadText] NULL,
	[CUST_ADDRESS]     [dbo].[LoadText] NULL,
	[CUST_DISTRICT]     [dbo].[LoadText] NULL,
	[CUST_CITY]     [dbo].[LoadText] NULL,
	[CUST_REGION]     [dbo].[LoadText] NULL,
	[CUST_POSTAL_CODE]     [dbo].[LoadText] NULL,
	[CUST_COUNTRY]     [dbo].[LoadText] NULL,
	[CUST_HOME_PH_NUMBER]     [dbo].[LoadText] NULL,
	[CUST_HOME_PH_EXTENSION]     [dbo].[LoadText] NULL,
	[CUST_BUS_PH_COUNTRY_CODE]     [dbo].[LoadText] NULL,
	[CUST_BUS_PH_NUMBER]     [dbo].[LoadText] NULL,
	[CUST_BUS_PH_EXTENSION]     [dbo].[LoadText] NULL,
	[CUST_BUS_PH_COUNTRY_CODE2]     [dbo].[LoadText] NULL,
	[CUST_HOME_EMAIL]     [dbo].[LoadText] NULL,
	[CUST_BUS_EMAIL]     [dbo].[LoadText] NULL,
	[CUST_BIRTH_DATE]     [dbo].[LoadText] NULL,
	[CUST_ALLOW_SOLICIT]     [dbo].[LoadText] NULL,
	[CUST_ALLOW_PHONE_SOLICIT]     [dbo].[LoadText] NULL,
	[CUST_ALLOW_EMAIL_SOLICIT]     [dbo].[LoadText] NULL,
	[CUST_ALLOW_MAIL_SOLICIT]     [dbo].[LoadText] NULL,
	[ODOMETER_IN]     [dbo].[LoadText] NULL,
	[ODOMETER_OUT]     [dbo].[LoadText] NULL,
	[VEHICLE_PICKUP_DATE]     [dbo].[LoadText] NULL,
	[APPOINTMENT_FLAG]     [dbo].[LoadText] NULL,
	[DEPARTMENT]     [dbo].[LoadText] NULL,
	[EXT_SVC_CONTRACT_NAMES]     [dbo].[LoadText] NULL,
	[PAYMENT_METHODS]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_PARTS_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_LABOR_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_MISC_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_SUBLET_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_GOG_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_TTL_MISC_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_PARTS_COST]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_LABOR_COST]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_MISC_COST]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_SUBLET_COST]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_GOG_COST]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_TTL_MISC_COST]     [dbo].[LoadText] NULL,
	[TOTAL_CUSTOMER_COST]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_PARTS_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_LABOR_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_MISC_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_SUBLET_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_GOG_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_TTL_MISC_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_PARTS_COST]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_LABOR_COST]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_MISC_COST]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_SUBLET_COST]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_GOG_COST]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_TTL_MISC_COST]     [dbo].[LoadText] NULL,
	[TOTAL_WARRANTY_COST]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_PARTS_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_LABOR_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_MISC_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_SUBLET_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_GOG_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_TTL_MISC_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_PARTS_COST]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_LABOR_COST]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_MISC_COST]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_SUBLET_COST]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_GOG_COST]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_TTL_MISC_COST]     [dbo].[LoadText] NULL,
	[TOTAL_INTERNAL_COST]     [dbo].[LoadText] NULL,
	[TOTAL_PARTS_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_LABOR_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_MISC_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_SUBLET_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_GOG_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_TTL_MISC_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_RO_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_TAX_PRICE]     [dbo].[LoadText] NULL,
	[TOTAL_PARTS_COST]     [dbo].[LoadText] NULL,
	[TOTAL_LABOR_COST]     [dbo].[LoadText] NULL,
	[TOTAL_MISC_COST]     [dbo].[LoadText] NULL,
	[TOTAL_SUBLET_COST]     [dbo].[LoadText] NULL,
	[TOTAL_GOG_COST]     [dbo].[LoadText] NULL,
	[TOTAL_TTL_MISC_COST]     [dbo].[LoadText] NULL,
	[TOTAL_RO_COST]     [dbo].[LoadText] NULL,
	[TOTAL_ACTUAL_LABOR_HOURS]     [dbo].[LoadText] NULL,
	[TOTAL_BILLED_LABOR_HOURS]     [dbo].[LoadText] NULL,
	[VEH_VIN]     [dbo].[LoadText] NULL,
	[VEH_MODEL_YEAR]     [dbo].[LoadText] NULL,
	[VEH_MAKE]     [dbo].[LoadText] NULL,
	[VEH_MODEL]     [dbo].[LoadText] NULL,
	[VEH_TRANS_TYPE]     [dbo].[LoadText] NULL,
	[VEH_EXT_COLOR_DESCRIPTION]     [dbo].[LoadText] NULL,
	[VEH_REG_LICENSE_PLATE_NUMBER]     [dbo].[LoadText] NULL,
	[OPERATIONS]     NVARCHAR(MAX) NULL,
	[TECH_COMMENT]     [dbo].[LoadText] NULL,
	[CUST_COMMENT]     [dbo].[LoadText] NULL,
	[SERVICE_ADVISOR_CONTACT_ID]     [dbo].[LoadText] NULL,
	[SERVICE_ADVISOR_FIRST_NAME]     [dbo].[LoadText] NULL,
	[SERVICE_ADVISOR_MIDDLE_NAME]     [dbo].[LoadText] NULL,
	[SERVICE_ADVISOR_LAST_NAME]     [dbo].[LoadText] NULL,
	[SERVICE_ADVISOR_SALUTATION]     [dbo].[LoadText] NULL,
	[SERVICE_ADVISOR_SUFFIX]     [dbo].[LoadText] NULL,
	[SERVICE_ADVISOR_FULL_NAME]     [dbo].[LoadText] NULL,
	
	TECHNICIAN_CONTACT_ID			[dbo].[LoadText] NULL,			-- Extracted from OPERATIONS column
	TECHNICIAN_FULL_NAME			[dbo].[LoadText] NULL,			-- Extracted from OPERATIONS column
	OPERATION_PAY_TYPE				[dbo].[LoadText] NULL,			-- Extracted from OPERATIONS column - 14-03-2017
	
	[Converted_RO_CLOSE_DATE] [datetime2](7) NULL,
	[Converted_CUST_BIRTH_DATE] [datetime2](7) NULL,
	[ManufacturerPartyID] [int] NULL,
	[SampleSupplierPartyID] [int] NULL,
	[CountryID] [smallint] NULL,
	[EventTypeID] [smallint] NULL,
	[LanguageID] [smallint] NULL,
	[DealerCodeOriginatorPartyID] [int] NULL,
	[SetNameCapitalisation] [bit] NULL,
	[SampleTriggeredSelectionReqID]   INT NULL,
	[CustomerIdentifierUsable] BIT NULL
)


*/