
CREATE TABLE [Stage].[Combined_IAssistance](
	[ID] INT IDENTITY(1,1) NOT NULL,
	[AuditID] [dbo].[AuditID] NULL,
	[PhysicalRowID] INT NULL,
		
	[Manufacturer] dbo.LoadText NULL,
	[CountryCode] dbo.LoadText NULL,
	[CountryCodeISOAlpha2] dbo.LoadText NULL,
	[EventType] dbo.LoadText NULL,
	[VehiclePurchaseDate] dbo.Loadtext NULL,
	[VehicleRegistrationDate] dbo.Loadtext NULL,
	[VehicleDeliveryDate] dbo.Loadtext NULL,
	[ServiceEventDate] dbo.Loadtext NULL,
	[DealerCode] dbo.LoadText NULL,
	[CustomerUniqueID] dbo.LoadText NULL,
	[CompanyName] dbo.LoadText NULL,

	[Title] dbo.LoadText NULL,
	[FirstName] dbo.LoadText NULL,
	[SurnameField1] dbo.LoadText NULL,
	[SurnameField2] dbo.LoadText NULL,

	[Salutation] dbo.LoadText NULL,
	[Address1] dbo.LoadText NULL,
	[Address2] dbo.LoadText NULL,
	[Address3] dbo.LoadText NULL,
	[Address4] dbo.LoadText NULL,
	[Address5(City)] dbo.LoadText NULL,
	[Address6(County)] dbo.LoadText NULL,
	[Address7(Postcode/Zipcode)] dbo.LoadText NULL,
	[Address8(Country)] dbo.LoadText NULL,
	[HomeTelephoneNumber] dbo.LoadText NULL,
	[BusinessTelephoneNumber] dbo.LoadText NULL,
	[MobileTelephoneNumber] dbo.LoadText NULL,
	[ModelName] dbo.LoadText NULL,
	[ModelYear] dbo.LoadText NULL,

	[VIN] dbo.LoadText NULL,
	[RegistrationNumber] dbo.LoadText NULL,

	[EmailAddress1] dbo.LoadText NULL,
	[EmailAddress2] dbo.LoadText NULL,
	[PreferredLanguage] dbo.LoadText NULL,
	[CompleteSuppression] dbo.LoadText NULL,
	[Suppression-Email] dbo.LoadText NULL,
	[Suppression-Phone] dbo.LoadText NULL,
	[Suppression-Mail] dbo.LoadText NULL,
	[InvoiceNumber] dbo.LoadText NULL,
	[InvoiceValue] dbo.LoadText NULL,
	[ServiceEmployeeCode] dbo.LoadText NULL,
	[EmployeeName] dbo.LoadText NULL,
	
	[OwnershipCycle] dbo.LoadText NULL,
	
	[Gender] dbo.LoadText NULL,
	[PrivateOwner] dbo.LoadText NULL,
	[OwningCompany] dbo.LoadText NULL,
	[User/ChooserDriver] dbo.LoadText NULL,
	[EmployerCompany] dbo.LoadText NULL,
	[MonthAndYearOfBirth] dbo.LoadText NULL,
	[PreferredMethodsOfContact] dbo.LoadText NULL,
	[PermissionsForContact] dbo.LoadText NULL,

	[DataSource] dbo.LoadText NULL,
	[IAssistanceProvider] dbo.LoadText NULL,
	[IAssistanceCallID] dbo.LoadText NULL,
	[IAssistanceCallStartDate] dbo.LoadText NULL,
	[ConvertedIAssistanceCallStartDate] [DATETIME2](7)  NULL,
	[IAssistanceCallCloseDate] dbo.LoadText NULL,
	[ConvertedIAssistanceCallCloseDate] [DATETIME2](7)  NULL,
	[IAssistanceHelpdeskAdvisorName] dbo.LoadText NULL,
	[IAssistanceHelpdeskAdvisorID] dbo.LoadText NULL,
	[IAssistanceCallMethod] dbo.LoadText NULL,
	
	PreferredLanguageID INT	NULL,
	SampleTriggeredSelectionReqID INT NULL
	
);