CREATE TABLE [Stage].[Global_LostLeads]
(
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[AuditID] [dbo].[AuditID] NULL,
	[PhysicalRowID] [int] NULL,
	[Manufacturer] [dbo].[LoadText] NULL,
	[CountryCode] [dbo].[LoadText] NULL,
	[EventType] [dbo].[LoadText] NULL,[DateOfLeadCreation] [dbo].[LoadText] NULL,
	[DateMarkedAsLostLead] [dbo].[LoadText] NULL,
	[DealerCode] [dbo].[LoadText] NULL,
	[CustomerUniqueID] [dbo].[LoadText] NULL,
	[CompanyName] [dbo].[LoadText] NULL,
	[Title] [dbo].[LoadText] NULL,
	[FirstName] [dbo].[LoadText] NULL,
	[SurnameField1] [dbo].[LoadText] NULL,
	[SurnameField2] [dbo].[LoadText] NULL,
	[Salutation] [dbo].[LoadText] NULL,
	[Address1]
	[dbo].[LoadText] NULL,
	[Address2] [dbo].[LoadText] NULL,
	[Address3] [dbo].[LoadText] NULL,
	[Address4] [dbo].[LoadText] NULL,
	[Address5] [dbo].[LoadText] NULL,
	[Address6] [dbo].[LoadText] NULL,
	[Address7] [dbo].[LoadText] NULL,
	[Address8] [dbo].[LoadText] NULL,
	[HomeTelephoneNumber] [dbo].[LoadText] NULL,
	[BusinessTelephoneNumber] [dbo].[LoadText] NULL,
	[MobileTelephoneNumber] [dbo].[LoadText] NULL,
	[ModelOfInterest] [dbo].[LoadText] NULL,
	[ModelYear] [dbo].[LoadText] NULL,
	[EmailAddress1] [dbo].[LoadText] NULL,
	[EmailAddress2] [dbo].[LoadText] NULL,
	[PreferredLanguage] [dbo].[LoadText] NULL,
	[MarketingPermission] [dbo].[LoadText] NULL,
	[NameOfSalesExecutive] [dbo].[LoadText] NULL,
	[Gender] [dbo].[LoadText] NULL,
	[CompleteSuppressionJLR] [dbo].[LoadText] NULL,
	[CompleteSuppressionRetailer] [dbo].[LoadText] NULL,
	[PermissionToEmailJLR] [dbo].[LoadText] NULL,
	[PermissionToEmailRetailer] [dbo].[LoadText] NULL,
	[PermissionToPhoneJLR] [dbo].[LoadText] NULL,
	[PermissionToPhoneRetailer] [dbo].[LoadText] NULL,
	[PermissionToPostJLR] [dbo].[LoadText] NULL,
	[PermissionToPostRetailer] [dbo].[LoadText] NULL,
	[PermissionToSMSJLR] [dbo].[LoadText] NULL,
	[PermissionToSMSRetailer] [dbo].[LoadText] NULL,
	[PermissionToSocialMediaJLR] [dbo].[LoadText] NULL,
	[PermissionToSocialMediaRetailer] [dbo].[LoadText] NULL,
	[DateOfLastContact] [dbo].[LoadText] NULL,
	[SuppressionEmail] [dbo].[LoadText] NULL,
	[SuppressionPhone] [dbo].[LoadText] NULL,
	[SuppressionMail] [dbo].[LoadText] NULL,
	[ConvertedDateOfLastContact] [datetime2](7) NULL,
	[ConvertedDateOfLeadCreation] [datetime2](7) NULL,
	[ConvertedDateMarkedAsLostLead] [datetime2](7) NULL,
	[ManufacturerPartyID] [int] NULL,
	[SampleSupplierPartyID] [int] NULL,
	[CountryID] [smallint] NULL,
	[EventTypeID] [smallint] NULL,
	[LanguageID] [smallint] NULL,
	[DealerCodeOriginatorPartyID] [int] NULL,
	[SetNameCapitalisation] [bit] NULL,
	[SampleTriggeredSelectionReqID]   INT NULL,
	[CustomerIdentifier] [dbo].[CustomerIdentifier] NULL,
	[CustomerIdentifierUsable] BIT NULL
)
