

CREATE TABLE [Stage].[Jaguar_Germany_Sales] (
    [ID]						INT            IDENTITY (1, 1) NOT NULL,
    [AuditID]					dbo.AuditID         NULL,
    [PhysicalRowID]				INT            NULL,
	[CompanyID]					dbo.LoadText NULL,
	[PersonID]					dbo.LoadText NULL,
	[DeliveryDate]				dbo.LoadText NULL,
	[DealerNO]					dbo.LoadText NULL,
	[VIN]						dbo.LoadText NULL,
	[RegDate]					dbo.LoadText NULL,
	[Model]						dbo.LoadText NULL,
	[PurchaseReason]			dbo.LoadText NULL,
	[CreateDate]				dbo.LoadText NULL,
	[TypeOfRegistration]		dbo.LoadText NULL,
	[VehicleUse]				dbo.LoadText NULL,
	[Company]					dbo.LoadText NULL,
	[COStreetHouseNo]			dbo.LoadText NULL,
	[COPostalCode]				dbo.LoadText NULL,
	[COCity]					dbo.LoadText NULL,
	[CoareaCode]				dbo.LoadText NULL,
	[CompanyExtension]			dbo.LoadText NULL,
	[Salutation]				dbo.LoadText NULL,
	[AcademicTitle]				dbo.LoadText NULL,
	[NobilityTitle]				dbo.LoadText NULL,
	[FirstName]					dbo.LoadText NULL,
	[LastName]					dbo.LoadText NULL,
	[PrivStreetHouseNo]		dbo.LoadText NULL,
	[PrivPostalCode]			dbo.LoadText NULL,
	[PrivCity]					dbo.LoadText NULL,
	[CustomerType]				dbo.LoadText NULL,
	[PrivateAreaCode]			dbo.LoadText NULL,
	[PrivateExtension]			dbo.LoadText NULL,
	[BusinessAreaCode]			dbo.LoadText NULL,
	[BusinessExtension]			dbo.LoadText NULL,
	[SalutatoryAddress]			dbo.LoadText NULL,
    [EmailAddress]				dbo.LoadText NULL,
    [ConvertedCreateDate]		DATETIME2    NULL,
    [ConvertedDeliveryDate]		DATETIME2	 NULL,
    [ConvertedRegDate]			DATETIME2	 NULL,
);

