CREATE TABLE [Stage].[Jaguar_Portugal_Service] (
    [ID]						INT          IDENTITY (1, 1) NOT NULL,
    [AuditID]					dbo.AuditID  NULL,
    [PhysicalRowID]				INT          NULL,
	[Title]						dbo.LoadText NULL,
	[Forename]					dbo.LoadText NULL,
	[Surname]					dbo.LoadText NULL,
	[Company]					dbo.LoadText NULL,
	[Address1]					dbo.LoadText NULL,
	[Address2]					dbo.LoadText NULL,
	[Address3]					dbo.LoadText NULL,
	[Address4]					dbo.LoadText NULL,
	[Address5]					dbo.LoadText NULL,
	[Address6]					dbo.LoadText NULL,
	[Address7]					dbo.LoadText NULL,
	[Address8]					dbo.LoadText NULL,
	[Address9]					dbo.LoadText NULL,
	[Postcode]					dbo.LoadText NULL,
	[SuppressionCode]			dbo.LoadText NULL,
	[TypeOfCustomer]			dbo.LoadText NULL,	
	[MobilePhone]				dbo.LoadText NULL,
	[BusinessPhone]				dbo.LoadText NULL,
	[HomePhone]					dbo.LoadText NULL,
	[VIN]						dbo.LoadText NULL,	
	[Modeldescription]			dbo.LoadText NULL,
	[RegistrationNumber]		dbo.LoadText NULL,
	[PaymentMethod]				dbo.LoadText NULL,
	[Dealercode]				dbo.LoadText NULL,
	[PurchaseDate]				dbo.LoadText NULL,
	[RegistrationDate]			dbo.LoadText NULL,
	[DeliveryDate]				dbo.LoadText NULL,
	[ServiceDate]				dbo.LoadText NULL,
	[TypeofWork]				dbo.LoadText NULL,
	[LanguageCode]				dbo.LoadText NULL,
	[CountryCode]				dbo.LoadText NULL,
	[EmailAddress]				dbo.LoadText NULL,
	[ExtraColumn]				dbo.LoadText NULL,
    [ConvertedRegistrationDate] DATETIME2    NULL,
    [ConvertedServiceDate]      DATETIME2    NULL,
    [ConvertedDeliveryDate]     DATETIME2    NULL,
    [ConvertedPurchaseDate]     DATETIME2    NULL
    
);

