CREATE TABLE [Stage].[Jaguar_Italy_Sales] (
    [ID]						INT          IDENTITY (1, 1) NOT NULL,
    [AuditID]					dbo.AuditID  NULL,
    [PhysicalRowID]				INT          NULL,
	[VIN]						dbo.LoadText NULL,
	[RegistrationNumber]		dbo.LoadText NULL,
	[SalesDate]					dbo.LoadText NULL,
	[Title]						dbo.LoadText NULL,
	[Blank1]					dbo.LoadText NULL,
	[ForeName]					dbo.LoadText NULL,
	[Surname]					dbo.LoadText NULL,
	[Address1]					dbo.LoadText NULL,
	[Address2]					dbo.LoadText NULL,
	[Address3]					dbo.LoadText NULL,
	[Address4]					dbo.LoadText NULL,
	[PostCode]					dbo.LoadText NULL,
	[Telephone]					dbo.LoadText NULL,
	[Type]						dbo.LoadText NULL,
	[Blank2]					dbo.LoadText NULL,
	[Gender]					dbo.LoadText NULL,
	[DealerCode]				dbo.LoadText NULL,
    [EmailAddress]				dbo.LoadText NULL,
    [ConvertedSalesDate]		DATETIME2    NULL
);

