CREATE TABLE Stage.LandRover_UK_Sales(
	ID							INT IDENTITY(1,1) NOT NULL,
	AuditID						dbo.AuditID NULL,
	PhysicalRowID				INT NULL,
	SalesDealerCode				dbo.LoadText NULL,
	WorldManufacturingID		dbo.LoadText NULL,
	VIN dbo.LoadText			NULL,
	RegistrationNumber			dbo.LoadText NULL,
	RegistrationDate			dbo.LoadText NULL,
	SalesDate					dbo.LoadText NULL,
	URN							dbo.LoadText NULL,
	Title						dbo.LoadText NULL,
	Initials					dbo.LoadText NULL,
	FirstName					dbo.LoadText NULL,
	CustomerName				dbo.LoadText NULL,
	CompanyName					dbo.LoadText NULL,
	Address1					dbo.LoadText NULL,
	Address2					dbo.LoadText NULL,
	Address3					dbo.LoadText NULL,
	Address4					dbo.LoadText NULL,
	Town						dbo.LoadText NULL,
	County						dbo.LoadText NULL,
	Postcode					dbo.LoadText NULL,
	ModelDescription			dbo.LoadText NULL,
	Telephone					dbo.LoadText NULL,
	EmailAddress				dbo.LoadText NULL,
	CompleteSuppression			dbo.LoadText NULL,
	MailSuppression				dbo.LoadText NULL,
	EmailSuppression			dbo.LoadText NULL,
	ConvertedRegistrationDate	datetime2(7) NULL,
	ConvertedSalesDate			datetime2(7) NULL,
	AFRLCode					dbo.LoadText NULL
	)
GO