CREATE TABLE [dbo].[VWT] (
    [VWTID]									dbo.VWTID						NOT NULL		IDENTITY(1,1),
-- GENERAL INFO 
	[LoadedDate]							DATETIME2						NOT NULL,  
    [AuditID]								dbo.AuditID						NOT NULL,
    [AuditItemID]							dbo.AuditItemID					NOT NULL,
    [PhysicalFileRow]						INT								NOT NULL,
    [ManufacturerID]						dbo.PartyID						NULL,
    [SampleSupplierPartyID]					dbo.PartyID						NULL,
    [MatchedODSPartyID]						dbo.PartyID						NOT NULL,
    
	[TypeOfSaleOrig]						VARCHAR(50)						NULL,
	[AFRLCode]								dbo.AFRLCode					NULL,
    [SuppliedIndustryClassificationID]		dbo.PartyTypeID					NULL,
    
    SampleTriggeredSelectionReqID			INT								NULL,
    PartyMatchingMethodologyID				INT								NULL,
    
-- PERSON INFO
	[PersonParentAuditItemID]				dbo.AuditItemID					NULL,
    [MatchedODSPersonID]					dbo.PartyID						NOT NULL,
    [Title]									dbo.Title						NULL,
    [TitleID]								dbo.TitleID						NOT NULL,
    [Initials]								dbo.NameDetail					NULL,
    [FirstNameOrig]							dbo.NameDetail					NULL,
    [FirstName]								dbo.NameDetail					NULL,
    [MiddleName]							dbo.NameDetail					NULL,
    [LastNameOrig]							dbo.NameDetail					NULL,
    [LastName]								dbo.NameDetail					NULL,
    [SecondLastNameOrig]					dbo.NameDetail					NULL,
    [SecondLastName]						dbo.NameDetail					NULL,
    [SetNameCapitalisation]					BIT								NOT NULL,
    [GenderID]								dbo.GenderID					NOT NULL,
    [BirthDate]								DATETIME2						NULL,
    [LanguageID]							dbo.LanguageID					NOT NULL,
    [CustomerIdentifier]					dbo.CustomerIdentifier			NULL,
    [CustomerIdentifierUsable]				BIT								NOT NULL,
    [CustomerIdentifierOriginatorPartyID]	dbo.PartyID						NOT NULL,
    [PartySuppression]						BIT								NOT NULL,
    
    [Salutation]							dbo.Salutation					NULL,
    
    
-- ORGANISATION INFO
	[OrganisationParentAuditItemID]			dbo.AuditItemID					NULL,
    [MatchedODSOrganisationID]				dbo.PartyID						NOT NULL,
    [OrganisationNameOrig]					dbo.OrganisationName			NULL,
    [OrganisationName]						dbo.OrganisationName			NULL,
    	
-- ADDRESS INFO
    [AddressParentAuditItemID]				dbo.AuditItemID					NULL,
    [MatchedODSAddressID]					dbo.ContactMechanismID			NOT NULL,
    [BuildingName]							dbo.AddressText					NULL,
    [SubStreetAndNumberOrig]				dbo.AddressText					NULL,
    [SubStreetOrig]							dbo.AddressText					NULL,
    [SubStreetNumber]						dbo.AddressNumberText			NULL,
    [SubStreet]								dbo.AddressText					NULL,
    [StreetAndNumberOrig]					dbo.AddressText					NULL,
    [StreetOrig]							dbo.AddressText					NULL,
    [StreetNumber]							dbo.AddressNumberText			NULL,
    [Street]								dbo.AddressText					NULL,
    [SubLocality]							dbo.AddressText					NULL,
    [Locality]								dbo.AddressText					NULL,
    [Town]									dbo.AddressText					NULL,
    [Region]								dbo.AddressText					NULL,
    [Postcode]								dbo.Postcode					NULL,
    [Country]								dbo.AddressText					NULL,
    [CountryID]								dbo.CountryID					NULL,
	[PostalSuppression]						BIT					            NOT NULL,
	[AddressChecksum]						BIGINT							NULL,
    
-- PHONE INFO
	[MatchedODSTelID]						dbo.ContactMechanismID			NULL,
    [Tel]									dbo.ContactNumber				NULL,
    [MatchedODSPrivTelID]					dbo.ContactMechanismID			NULL,
    [PrivTel]								dbo.ContactNumber				NULL,
    [MatchedODSBusTelID]					dbo.ContactMechanismID			NULL,
    [BusTel]								dbo.ContactNumber				NULL,
    [MatchedODSMobileTelID]					dbo.ContactMechanismID			NULL,
    [MobileTel]								dbo.ContactNumber				NULL,
    [MatchedODSPrivMobileTelID]				dbo.ContactMechanismID			NULL,
    [PrivMobileTel]							dbo.ContactNumber				NULL,
    
-- EMAIL INFO
    [MatchedODSEmailAddressID]				dbo.ContactMechanismID			NULL,
    [EmailAddress]							dbo.EmailAddress				NULL,
	[MatchedODSPrivEmailAddressID]			dbo.ContactMechanismID			NULL,
    [PrivEmailAddress]						dbo.EmailAddress				NULL,
	[EmailSuppression]						BIT								NOT NULL,
    
-- VEHICLE INFO
	[VehicleParentAuditItemID]				dbo.AuditItemID					NULL,
    [MatchedODSVehicleID]					dbo.VehicleID					NOT NULL,
    [VehicleIdentificationNumber]			dbo.VIN							NULL,
    [VehicleIdentificationNumberUsable]		BIT								NOT NULL,
    [ODSRegistrationID]						dbo.RegistrationID				NULL,
    [VehicleRegistrationNumber]				dbo.RegistrationNumber			NULL,
    [RegistrationDateOrig]					VARCHAR(20)						NULL,
    [RegistrationDate]						DATETIME2						NULL,
    [MatchedODSModelID]						dbo.ModelID						NULL,
    [ModelDescription]						dbo.VehicleDescription			NULL,
    [BodystyleDescription]					dbo.VehicleDescription			NULL,
    [EngineDescription]						dbo.VehicleDescription			NULL,
    [TransmissionDescription]				dbo.VehicleDescription			NULL,
    [Driverindicator]						BIT								NULL,
    [OwnerIndicator]						BIT								NULL,
    [ManagerIndicator]                      BIT								NULL,
    [OwnershipCycle]						dbo.OwnershipCycle				NULL,
    [BuildDateOrig]							VARCHAR(20)						NULL,
    [BuildYear]								SMALLINT						NULL,
    
-- EVENT INFO
	[MatchedODSEventID]						dbo.EventID						NOT NULL,
    [ODSEventTypeID]						dbo.EventTypeID					NULL,
    [SaleDateOrig]							VARCHAR(20)						NULL,
    [SaleDate]								DATETIME2						NULL,
    [ServiceDateOrig]						VARCHAR(20)						NULL,
    [ServiceDate]							DATETIME2						NULL,
    [RoadsideDateOrig]						VARCHAR(20)						NULL,
    [RoadsideDate]							DATETIME2						NULL,
    [CRCDateOrig]							VARCHAR(30)						NULL,
    [CRCDate]								DATETIME2						NULL,
    [LostLeadDateOrig]						VARCHAR(30)						NULL,
    [LostLeadDate]							DATETIME2						NULL,
    [InvoiceDateOrig]						VARCHAR(20)						NULL,
    [InvoiceDate]							DATETIME2						NULL,
    [IAssistanceDateOrig]					VARCHAR(20)						NULL,		-- BUG 15056
    [IAssistanceDate]						DATETIME2						NULL,		-- BUG 15056
	[GeneralEnquiryDateOrig]				VARCHAR(20)						NULL,
	[GeneralEnquiryDate]					DATETIME2						NULL,

	[LandRoverExperienceDateOrig]			varchar(20)						NULL,		-- TASK 879
	[LandRoverExperienceDate]				datetime2(7)					NULL,		-- TASK 879

	[WarrantyID]                            dbo.WarrantyID					NULL,
	[RoadsideID]							dbo.RoadsideID					NULL,
	[CRC_ID]								dbo.CRCEventID					NULL,
	[IAssistanceID]							INT								NULL,		-- BUG 15056
	[GeneralEnquiryID]						INT								NULL,
	
	[LandRoverExperienceID]					varchar(20)						NULL,		-- TASK 879

-- DEALER INFO
	[SalesDealerCodeOriginatorPartyID]		dbo.PartyID						NULL,
    [SalesDealerCode]						dbo.DealerCode					NULL,
    [SalesDealerID]							dbo.PartyID						NOT NULL,
    [ServiceDealerCodeOriginatorPartyID]	dbo.PartyID						NULL,
    [ServiceDealerCode]						dbo.DealerCode					NULL,
    [ServiceDealerID]						dbo.PartyID						NOT NULL,
    [Approved]								dbo.Approved					NULL,
    
-- ROADSIDE NETWORK INFO	
	[RoadsideNetworkOriginatorPartyID]		dbo.PartyID						NULL,
	[RoadsideNetworkCode]					dbo.RoadsideNetworkCode			NULL,  
	[RoadsideNetworkPartyID]				dbo.PartyID						NULL,

-- CRC NETWORK INFO	
	[CRCCentreOriginatorPartyID]			dbo.PartyID						NULL,
	[CRCCentreCode]							dbo.CRCNetworkCode				NULL,  
	[CRCCentrePartyID]						dbo.PartyID						NULL,	

-- IASSISTANCE NETWORK INFO	
	[IAssistanceCentreOriginatorPartyID]	dbo.PartyID						NULL,		-- BUG 15056
	[IAssistanceCentreCode]					NVARCHAR(50)					NULL,		-- BUG 15056
	[IAssistanceCentrePartyID]				dbo.PartyID						NULL,		-- BUG 15056
	
-- ADDITIONAL VISTA SALES INFO
	[SalesOrderNumber]						dbo.AddressText					NULL,						 
	[SalesCustomerType]						dbo.AddressText					NULL,						 
	[SalesPaymentType]						dbo.AddressText					NULL,						 
	[Salesman]								dbo.AddressText					NULL,						 
	[ContractRelationship]					dbo.AddressText					NULL,						 
	[ContractCustomer]						dbo.AddressText					NULL,						 
	[SalesmanCode]							dbo.AddressText					NULL,    
	[AdditionalCountry]						dbo.AddressText					NULL,
	[State]									dbo.AddressText					NULL,
 
 
-- ADDITIONAL INFO 
	LostLead_DateOfLeadCreationOrig			VARCHAR(30)						NULL,
	[ServiceAdvisorID]						dbo.AddressText					NULL,						 
	[ServiceAdvisorName]					dbo.AddressText					NULL,						 
	[TechnicianID]							dbo.AddressText					NULL,						 
	[TechnicianName]						dbo.AddressText					NULL,						 
	[VehicleSalePrice]						dbo.AddressText					NULL,						 
	[SalesAdvisorID]						dbo.AddressText					NULL,						 
	[SalesAdvisorName]						dbo.AddressText					NULL,	
	[PDI_Flag]								VARCHAR(1)						NULL,			-- BUG 14122 - 31/08/2017				 
    
-- NETHERLANDS SERVICE EVENT DRIVEN SETUP
	[VehiclePurchaseDate]					VARCHAR(20)						NULL,
	[VehicleDeliveryDate]					VARCHAR(20)						NULL,
	[JLRSuppliedEventType]					dbo.EventTypeID					NULL,
	[InvoiceNumber]							dbo.AddressText					NULL,
	[InvoiceValue]							dbo.AddressText					NULL,
	[PrivateOwner]							dbo.AddressText					NULL,
	[OwningCompany]							dbo.AddressText					NULL,
	[UserChooserDriver]						dbo.AddressText					NULL,
	[EmployerCompany]						dbo.AddressText					NULL,
	[MonthAndYearOfBirth]					dbo.NameDetail					NULL,
    [PhoneSuppression]						BIT								NULL,
    [PreferredMethodOfContact]				dbo.NameDetail					NULL,
    
    [EventParentAuditItemID]				dbo.AuditItemID			        NULL,
 	[LostLead_DateOfLeadCreation]			VARCHAR(30)						NULL,
   
	[BodyShopEventDateOrig]					VARCHAR (30)                NULL,
    [BodyShopEventDate]						DATETIME2 (7)               NULL,
	[BodyshopDealerCode]					[dbo].[DealerCode]          NULL,
    [BodyshopDealerID]						[dbo].[PartyID]             NULL,
    [BodyshopDealerCodeOriginatorPartyID]	[dbo].[PartyID]             NULL,
    
    -- LOST LEAD ADDITIONAL INFO : BUG 14820 - Lost Leads -  Globa loader change
    LostLead_MarketingPermission					VARCHAR(20)						NULL,
    LostLead_CompleteSuppressionJLR					VARCHAR(20)						NULL,
	LostLead_CompleteSuppressionRetailer			VARCHAR(20)						NULL,
	LostLead_PermissionToEmailJLR					VARCHAR(20)						NULL,
	LostLead_PermissionToEmailRetailer				VARCHAR(20)						NULL,
	LostLead_PermissionToPhoneJLR					VARCHAR(20)						NULL,
	LostLead_PermissionToPhoneRetailer				VARCHAR(20)						NULL,
	LostLead_PermissionToPostJLR					VARCHAR(20)						NULL,
	LostLead_PermissionToPostRetailer				VARCHAR(20)						NULL,
	LostLead_PermissionToSMSJLR						VARCHAR(20)						NULL,
	LostLead_PermissionToSMSRetailer				VARCHAR(20)						NULL,
	LostLead_PermissionToSocialMediaJLR				VARCHAR(20)						NULL,
	LostLead_PermissionToSocialMediaRetailer		VARCHAR(20)						NULL,
	LostLead_DateOfLastContact						VARCHAR(20)						NULL,
	LostLead_ConvertedDateOfLastContact				DATETIME2						NULL, 
    [RONumber]										VARCHAR(100)					NULL,

	[MatchedModelVariantID]							SMALLINT						NULL,
	[MatchedModelYear]								SMALLINT						NULL,
	[ExperienceDealerCode]							[dbo].[DealerCode]				NULL, --TASK 877 - Land Rover Experience	
    [ExperienceDealerCodeOriginatorPartyID]			[dbo].[PartyID]					NULL, --TASK 877 - Land Rover Experience
	[ExperienceDealerID]							[dbo].[PartyID]					NULL, --TASK 877 - Land Rover Experience
	[CommonSaleType]								dbo.AddressText					NULL, --TASK 900 - Business & Fleet Vehicle changes 
	[TypeOfSaleID]									dbo.AddressText					NULL  --TASK 900 - Business & Fleet Vehicle changes 
   /* WARRANTY
   
   [ClaimNumber]                           NCHAR (7)       NULL,
   [CLAIMSTATUS]                           CHAR (1)        NULL,
   [WIAA02_CLAIM_TYPE_C]                   CHAR (1)        NULL,
   [COVERAGECATEGORY]                      VARCHAR (100)   NULL,
   [PROGRAMCODE]                           VARCHAR (100)   NULL,
   [WIAA02_TOTAL_LABOR_A]                  VARCHAR (100)   NULL,
   [ComplaintCode]                         NCHAR (6)       NULL,
   [DistanceUnit]                          NCHAR (1)       NULL,
   [ClaimType]                             TINYINT         NULL
   [ISOCountryCode]                        CHAR (3)        NULL,
   [RONumber]                              VARCHAR (50)    NULL,
     
    */
    
    /* NOT USED
    [BuildingNameOrig]						dbo.AddressText	NULL,
    [LogicalFileRow]                        INT             NOT NULL,
    [LanguageDesc]                          NVARCHAR (100)  NULL,
    [InitialsOrig]                          NVARCHAR (20)   NULL,
    [MiddleNameOrig]                        NVARCHAR (140)  NULL,
    [ProperCaseName]                        BIT             NOT NULL,
    [SurnameSuffix]                         CHAR (10)       NULL,
    [PostNominalTitleID]                    SMALLINT        NULL,
    [PostNominalTitle]                      NVARCHAR (140)  NULL,
    [FullnamePronunciation]                 NVARCHAR (400)  NULL,
    [Nickname]                              NVARCHAR (100)  NULL,
    [JointOwnerPreNominalTitleID]           SMALLINT        NULL,
    [JointOwnerPreNominalTitle]             NVARCHAR (140)  NULL,
    [JointOwnerInitials]                    NVARCHAR (20)   NULL,
    [JointOwnerFirstName]                   NVARCHAR (140)  NULL,
    [JointOwnerMiddleName]                  NVARCHAR (140)  NULL,
    [JointOwnerLastName]                    NVARCHAR (140)  NULL,
    [JointOwnerSecondLastName]              NVARCHAR (140)  NULL,
    [JointOwnerPostNominalTitleID]          SMALLINT        NULL,
    [JointOwnerPostNominalTitle]            NVARCHAR (140)  NULL,
    [EmploymentPosition]                    NVARCHAR (100)  NULL,
    [EmploymentPositionTypeID]              INT             NULL,
    [OrganisationPronunciation]             NVARCHAR (400)  NULL,
    [JointOwnershipName]                    NVARCHAR (300)  NULL,
    [JointOwnerGenderID]                    TINYINT         NULL,
    [PurchaseTypeID]                        SMALLINT        NULL,
    [CustomerStatusID]                      SMALLINT        NULL,
    [CupidOccupationTypeDescription]        NVARCHAR (200)  NULL,
    [CupidCustomerSuppressionCode]          NVARCHAR (50)   NULL,
    [CupidLocalSalesType]                   NVARCHAR (10)   NULL,
    [CupidGlobalSalesType]                  NVARCHAR (10)   NULL,
    [MaritalStatusID]                       TINYINT         NULL,
    [BirthDateOrig]                         VARCHAR (20)    NULL,
    [BirthDateEstimated]                    BIT             NULL,
    [PrivTelPref]                           NVARCHAR (70)   NULL,
    [PrivTel2]                              NVARCHAR (70)   NULL,
    [BusMobileTel]                          NVARCHAR (70)   NULL,
    [Fax]                                   NVARCHAR (70)   NULL,
    [PrivFax]                               NVARCHAR (70)   NULL,
    [BusFax]                                NVARCHAR (70)   NULL,
    [PrivEmailAddress]                      NVARCHAR (200)  NULL,
    [BusEmailAddress]                       NVARCHAR (200)  NULL,
    [WebSiteURL]                            NVARCHAR (200)  NULL,
    [AddressPrefix]                         NVARCHAR (200)  NULL,
    [POBox]                                 NVARCHAR (40)   NULL,
    [CEDEX]                                 BIT             NOT NULL,
    [CEDEXNumber]                           NVARCHAR (15)   NULL,
    [FullAddressPronunciation]              NVARCHAR (1000) NULL,
    [VehicleProductCode]                    NVARCHAR (100)  NULL,
    [MatchedODSVehicleProductID]            INT             NULL,
    [ModelID]                               SMALLINT        NULL,
    [DerivativeDescription]                 VARCHAR (50)    NULL,
    [ColourDescription]                     VARCHAR (50)    NULL,
    [TrimColourDescription]                 VARCHAR (50)    NULL,
    [EOCCode]                               VARCHAR (50)    NULL,
    [BuildDate]                             DATETIME        NULL,
    [BuildMonth]                            TINYINT         NULL,
    [BuildDay]                              TINYINT         NULL,
    [DisposalDate]                          DATETIME        NULL,
    [CupidSalesmanCode]                     NVARCHAR (20)   NULL,
    [DealerCountryID]                       SMALLINT        NULL,
    [JointOwnerParentAuditItemID]           INT             NOT NULL,
    [CSPContact]                            BIT             NOT NULL,
    [MatchedODSJointOwnerID]                INT             NOT NULL,
    [MatchedODSJointOwnershipPartyID]       INT             NOT NULL,
    [MatchedODSEmploymentPositionID]        INT             NULL,
    [MatchedODSEmploymentPositionTypeID]    INT             NULL,
    [MatchedODSOrganisationRating]          DECIMAL (5, 2)  NULL,
    [MatchedODSPrivTel2ID]                  INT             NULL,
    [MatchedODSPrivTelPrefID]               INT             NULL,
    [MatchedODSBusMobileTelID]              INT             NULL,
    [MatchedODSFaxID]                       INT             NULL,
    [MatchedODSPrivFaxID]                   INT             NULL,
    [MatchedODSBusFaxID]                    INT             NULL,
    [MatchedODSPrivEmailAddressID]          INT             NULL,
    [MatchedODSBusEmailAddressID]           INT             NULL,
    [MatchedODSWebSiteURLID]                INT             NULL,
    [ODSTransferActionID]                   TINYINT         NULL,
    [ODSTransferActionDate]                 SMALLDATETIME   NULL,
    [UPUStreetID]                           INT             NULL,
    [UPUStreetIDValidate]                   INT             NULL,
    [FlgOrganisationTypeStandardised]       BIT             NULL,
    [FlgAddressPrefixExtracted]             BIT             NULL,
    [FlgSubStreetNumberExtracted]           BIT             NULL,
    [FlgSubStreetTypeStandardised]          BIT             NULL,
    [FlgStreetNumberExtracted]              BIT             NOT NULL,
    [FlgStreetTypeStandardised]             CHAR (10)       NULL,
    [FlgRowProcessed]                       BIT             NULL,
    [VINPrefix]                             NVARCHAR (30)   NULL,
    [FuelType]                              VARCHAR (50)    NULL,
    [JointOwnerInitialsOrig]                NVARCHAR (20)   NULL,
    [JointOwnerFirstNameOrig]               NVARCHAR (140)  NULL,
    [JointOwnerMiddleNameOrig]              NVARCHAR (140)  NULL,
    [JointOwnerLastNameOrig]                NVARCHAR (140)  NULL,
    [JointOwnerSecondLastNameOrig]          NVARCHAR (140)  NULL,
    [CampaignContactSourceCode]             NVARCHAR (50)   NULL,
    [CampaignSourceCode]                    NVARCHAR (50)   NULL,
    [SurveyType]                            VARCHAR (50)    NULL,
    [NewVehicleFlag]                        CHAR (1)        NULL,
    [CertifiedPreOwnerFlag]                 CHAR (1)        NULL,
    [SalesAssociatePassportID]              NVARCHAR (50)   NULL,
    [SalesAssociateFirstname]               NVARCHAR (50)   NULL,
    [SalesAssociateLastname]                NVARCHAR (50)   NULL,
    [ServiceAssociatePassportID]            NVARCHAR (50)   NULL,
    [ServiceAssociateFirstname]             NVARCHAR (50)   NULL,
    [ServiceAssociateLastname]              NVARCHAR (50)   NULL,
    [SRNumber]                              NVARCHAR (50)   NULL,
    [SRCategory]                            NVARCHAR (50)   NULL,
    [SRSubCategory]                         NVARCHAR (50)   NULL,
    [SRIssue]                               NVARCHAR (50)   NULL,
    [SRClosureDate]                         NVARCHAR (50)   NULL,
    [MatchedODSSalesAssociatePartyID]       INT             NULL,
    [MatchedODSServiceAssociatePartyID]     INT             NULL,
    [MatchedODSTechnicalAssociatePartyID]   INT             NULL,
    [SalesAssociateParentAuditItemID]       INT             NULL,
    [ServiceAssociateParentAuditItemID]     INT             NULL,
    [TechnicalAssociateParentAuditItemID]   INT             NULL,
    [TechnicalAssociatePassportID]          NVARCHAR (50)   NULL,
    [TechnicalAssociateFirstname]           NVARCHAR (50)   NULL,
    [TechnicalAssociateLastname]            NVARCHAR (50)   NULL,
    [Opportunity]                           NVARCHAR (100)  NULL,
    [OpportunityCreateDate]                 NVARCHAR (50)   NULL,
    [OpportunityType]                       NVARCHAR (100)  NULL,
    [OpportunityProduct]                    NVARCHAR (100)  NULL,
    [WarrantyType]                          NVARCHAR (100)  NULL,
    [MatchedODSSalesAssociateFirstName]     NVARCHAR (50)   NULL,
    [MatchedODSSalesAssociateLastName]      NVARCHAR (50)   NULL,
    [ODSSalesAssociateNameUpdate]           BIT             NOT NULL,
    [MatchedODSServiceAssociateFirstName]   NVARCHAR (50)   NULL,
    [MatchedODSServiceAssociateLastName]    NVARCHAR (50)   NULL,
    [ODSServiceAssociateNameUpdate]         BIT             NULL,
    [MatchedODSTechnicalAssociateFirstName] NVARCHAR (50)   NULL,
    [MatchedODSTechnicalAssociateLastName]  NVARCHAR (50)   NULL,
    [ODSTechnicalAssociateNameUpdate]       BIT             NULL,
    [ROSeqNumber]                           CHAR (1)        NULL,
    [OdometerDistance]                      SMALLINT        NULL,
    
    */
);

