ALTER TABLE [Audit].[ContactPreferencesBySurvey]
    ADD CONSTRAINT [PK_ContactPreferencesBySurvey] 
    PRIMARY KEY CLUSTERED ([AuditItemID] ASC, EventCategoryID ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

