ALTER TABLE [Audit].[Organisations]
    ADD CONSTRAINT [PK_Organisations] PRIMARY KEY CLUSTERED ([PartyID] ASC, [AuditItemID] ASC) 
    WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

