ALTER TABLE [Audit].[PostalAddresses]
    ADD CONSTRAINT [PK_PostalAddresses] PRIMARY KEY CLUSTERED ([AuditItemID] ASC, [ContactMechanismID] ASC) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

