CREATE NONCLUSTERED INDEX [IX_SampleQualityAndSelectionLogging_MarketPlus] ON [dbo].[SampleQualityAndSelectionLogging] 
([Market])
INCLUDE ([AuditItemID],[CaseID]) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 88) ON [PRIMARY]
GO
