CREATE TABLE [CRM].[Vista_Contract_Sales](
	[ID]										INT IDENTITY(1,1) NOT NULL,
	AuditID										dbo.AuditID NULL,
	VWTID										dbo.VWTID NULL,
	AuditItemID									dbo.AuditItemID NULL,
	PhysicalRowID								INT NOT NULL,
	Converted_ACCT_DATE_OF_BIRTH				DATETIME2(7) NULL,
	Converted_ACCT_DATE_ADVISED_OF_DEATH		DATETIME2(7) NULL,
	Converted_VEH_REGISTRATION_DATE				DATETIME2(7) NULL,
	Converted_VEH_BUILD_DATE					DATETIME2(7) NULL,
	Converted_DMS_REPAIR_ORDER_CLOSED_DATE		DATETIME2(7) NULL,
	Converted_ROADSIDE_DATE_JOB_COMPLETED		DATETIME2(7) NULL,
	Converted_CASE_CASE_SOLVED_DATE				DATETIME2(7) NULL,
	Converted_VISTACONTRACT_HANDOVER_DATE		DATETIME2(7) NULL,
	DateTransferredToVWT						DATETIME2(7) NULL, 
	SampleTriggeredSelectionReqID				INT	NULL,
	Calculated_Salutation						NVARCHAR(510) NULL,			-- BUG 16731
	Calculated_Title							NVARCHAR(510) NULL,			-- BUG 16731
	AFRLCode									dbo.LoadText NULL,
	item_Id							INT NULL,								-- TASK 502
	ACCT_ACADEMIC_TITLE				NVARCHAR(40) NULL,
	ACCT_ACADEMIC_TITLE_CODE		NVARCHAR(4) NULL,
	ACCT_ACCT_ID					NVARCHAR(10) NULL,
	ACCT_ACCT_TYPE					NVARCHAR(60) NULL,
	ACCT_ACCT_TYPE_CODE				NVARCHAR(1) NULL,
	ACCT_ADDITIONAL_LAST_NAME		NVARCHAR(40) NULL,
	ACCT_BP_ROLE					NVARCHAR(255) NULL,
	ACCT_BUILDING					NVARCHAR(20) NULL,
	ACCT_CITY_CODE					NVARCHAR(12) NULL,
	ACCT_CITY_CODE2					NVARCHAR(12) NULL,
	ACCT_CITY_TOWN					NVARCHAR(40) NULL,
	ACCT_CITYH_CODE					NVARCHAR(12) NULL,
	ACCT_CONSENT_JAGUAR_EMAIL		NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_PHONE		NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_POST		NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_EMAIL	NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_POST	NVARCHAR(60) NULL,
	ACCT_CONSENT_LR_PHONE			NVARCHAR(60) NULL,
	ACCT_CORRESPONDENCE_LANG_CODE	NVARCHAR(2) NULL,
	ACCT_CORRESPONDENCE_LANGUAGE	NVARCHAR(16) NULL,
	ACCT_COUNTRY					NVARCHAR(50) NULL,
	ACCT_COUNTRY_CODE				NVARCHAR(3) NULL,
	ACCT_COUNTY						NVARCHAR(40) NULL,
	ACCT_COUNTY_CODE				NVARCHAR(8) NULL,
	ACCT_DATE_ADVISED_OF_DEATH		NVARCHAR(10) NULL,
	ACCT_DATE_DECL_TO_GIVE_EMAIL	NVARCHAR(10) NULL,
	ACCT_DATE_OF_BIRTH				NVARCHAR(10) NULL,
	ACCT_DEAL_FULNAME_OF_CREAT_DEA	NVARCHAR(81) NULL,
	ACCT_DISTRICT					NVARCHAR(8) NULL,
	ACCT_EMAIL_VALIDATION_STATUS    NVARCHAR(30) NULL,
	ACCT_EMPLOYER_NAME				NVARCHAR(35) NULL,
	ACCT_EXTERN_FINANC_COMP_ACCTID  NVARCHAR(60) NULL,
	ACCT_FIRST_NAME					NVARCHAR(40) NULL,
	ACCT_FLOOR						NVARCHAR(10) NULL,
	ACCT_FULL_NAME					NVARCHAR(81) NULL,
	ACCT_GENDER_FEMALE				NVARCHAR(1) NULL,
	ACCT_GENDER_MALE				NVARCHAR(1) NULL,
	ACCT_GENDER_UNKNOWN				NVARCHAR(1) NULL,
	ACCT_GENERATION					NVARCHAR(5) NULL,
	ACCT_HOME_CITY					NVARCHAR(40) NULL,
	ACCT_HOME_EMAIL_ADDR_PRIMARY    NVARCHAR(241) NULL,
	ACCT_HOME_PHONE_NUMBER			NVARCHAR(30) NULL,
	ACCT_HOUSE_NO					NVARCHAR(10) NULL,
	ACCT_HOUSE_NUM2					NVARCHAR(10) NULL,
	ACCT_HOUSE_NUM3					NVARCHAR(10) NULL,
	ACCT_INDUSTRY_SECTOR			NVARCHAR(20) NULL,
	ACCT_INDUSTRY_SECTOR_CODE       NVARCHAR(10) NULL,
	ACCT_INITIALS					NVARCHAR(10) NULL,
	ACCT_JAGUAR_IN_MARKET_DATE      NVARCHAR(10) NULL,
	ACCT_JAGUAR_LOYALTY_STATUS      NVARCHAR(25) NULL,
	ACCT_KNOWN_AS					NVARCHAR(40) NULL,
	ACCT_LAND_ROVER_LOYALTY_STATUS  NVARCHAR(25) NULL,
	ACCT_LAND_ROVER_MARKET_DATE     NVARCHAR(10) NULL,
	ACCT_LAST_NAME					NVARCHAR(40) NULL,
	ACCT_LOCATION					NVARCHAR(40) NULL,
	ACCT_MIDDLE_NAME				NVARCHAR(40) NULL,
	ACCT_MOBILE_NUMBER				NVARCHAR(30) NULL,
	ACCT_NAME_1						NVARCHAR(40) NULL,
	ACCT_NAME_2						NVARCHAR(40) NULL,
	ACCT_NAME_3						NVARCHAR(40) NULL,
	ACCT_NAME_4						NVARCHAR(40) NULL,
	ACCT_NAME_CO					NVARCHAR(40) NULL,
	ACCT_NON_ACADEMIC_TITLE			NVARCHAR(80) NULL,
	ACCT_NON_ACADEMIC_TITLE_CODE    NVARCHAR(4) NULL,
	ACCT_ORG_TYPE					NVARCHAR(40) NULL,
	ACCT_ORG_TYPE_CODE				NVARCHAR(4) NULL,
	ACCT_PCODE1_EXT					NVARCHAR(10) NULL,
	ACCT_PCODE2_EXT					NVARCHAR(10) NULL,
	ACCT_PCODE3_EXT					NVARCHAR(10) NULL,
	ACCT_PO_BOX						NVARCHAR(10) NULL,
	ACCT_PO_BOX_CTY					NVARCHAR(3) NULL,
	ACCT_PO_BOX_LOBBY				NVARCHAR(40) NULL,
	ACCT_PO_BOX_LOC					NVARCHAR(40) NULL,
	ACCT_PO_BOX_NUM					NVARCHAR(1) NULL,
	ACCT_PO_BOX_REG					NVARCHAR(3) NULL,
	ACCT_POST_CODE2					NVARCHAR(10) NULL,
	ACCT_POST_CODE3					NVARCHAR(10) NULL,
	ACCT_POSTALAREA					NVARCHAR(15) NULL,
	ACCT_POSTCODE_ZIP				NVARCHAR(10) NULL,
	ACCT_PREF_CONTACT_METHOD		NVARCHAR(20) NULL,
	ACCT_PREF_CONTACT_METHOD_CODE   NVARCHAR(3) NULL,
	ACCT_PREF_CONTACT_TIME			NVARCHAR(30) NULL,
	ACCT_PREF_LANGUAGE				NVARCHAR(16) NULL,
	ACCT_PREF_LANGUAGE_CODE			NVARCHAR(2) NULL,
	ACCT_REGION_STATE				NVARCHAR(25) NULL,
	ACCT_REGION_STATE_CODE			NVARCHAR(3) NULL,
	ACCT_ROOM_NUMBER				NVARCHAR(10) NULL,
	ACCT_STREET						NVARCHAR(60) NULL,
	ACCT_STREETABBR					NVARCHAR(2) NULL,
	ACCT_STREETCODE					NVARCHAR(12) NULL,
	ACCT_SUPPLEMENT_1				NVARCHAR(40) NULL,
	ACCT_SUPPLEMENT_2				NVARCHAR(40) NULL,
	ACCT_SUPPLEMENT_3				NVARCHAR(40) NULL,
	ACCT_TITLE						NVARCHAR(30) NULL,
	ACCT_TITLE_CODE					NVARCHAR(4) NULL,
	ACCT_TOWNSHIP					NVARCHAR(40) NULL,
	ACCT_TOWNSHIP_CODE				NVARCHAR(8) NULL,
	ACCT_VIP_FLAG					NVARCHAR(1) NULL,
	ACCT_WORK_PHONE_EXTENSION       NVARCHAR(10) NULL,
	ACCT_WORK_PHONE_PRIMARY			NVARCHAR(30) NULL,
	ACTIVITY_ID						NVARCHAR(12) NULL,
	CAMPAIGN_CAMPAIGN_CHANNEL       NVARCHAR(40) NULL,
	CAMPAIGN_CAMPAIGN_DESC			NVARCHAR(40) NULL,
	CAMPAIGN_CAMPAIGN_ID			NVARCHAR(24) NULL,
	CAMPAIGN_CATEGORY_1				NVARCHAR(24) NULL,
	CAMPAIGN_CATEGORY_2				NVARCHAR(40) NULL,
	CAMPAIGN_CATEGORY_3				NVARCHAR(40) NULL,
	CAMPAIGN_DEALERFULNAME_DEALER1  NVARCHAR(81) NULL,
	CAMPAIGN_DEALERFULNAME_DEALER2  NVARCHAR(81) NULL,
	CAMPAIGN_DEALERFULNAME_DEALER3  NVARCHAR(81) NULL,
	CAMPAIGN_DEALERFULNAME_DEALER4  NVARCHAR(81) NULL,
	CAMPAIGN_DEALERFULNAME_DEALER5  NVARCHAR(81) NULL,
	CAMPAIGN_SECDEALERCODE_DEALER1  NVARCHAR(60) NULL,
	CAMPAIGN_SECDEALERCODE_DEALER2  NVARCHAR(60) NULL,
	CAMPAIGN_SECDEALERCODE_DEALER3  NVARCHAR(60) NULL,
	CAMPAIGN_SECDEALERCODE_DEALER4  NVARCHAR(60) NULL,
	CAMPAIGN_SECDEALERCODE_DEALER5  NVARCHAR(60) NULL,
	CAMPAIGN_TARGET_GROUP_DESC      NVARCHAR(72) NULL,
	CAMPAIGN_TARGET_GROUP_ID		NVARCHAR(10) NULL,
	CASE_BRAND						NVARCHAR(20) NULL,
	CASE_BRAND_CODE					NVARCHAR(20) NULL,
	CASE_CASE_CREATION_DATE			NVARCHAR(10) NULL,
	CASE_CASE_DESC					NVARCHAR(40) NULL,
	CASE_CASE_EMPL_RESPONSIBLE_NAM  NVARCHAR(81) NULL,
	CASE_CASE_ID					NVARCHAR(10) NULL,
	CASE_CASE_SOLVED_DATE			NVARCHAR(10) NULL,
	CASE_EMPL_RESPONSIBLE_ID		NVARCHAR(10) NULL,
	CASE_GOODWILL_INDICATOR			NVARCHAR(1) NULL,
	CASE_REASON_FOR_STATUS			NVARCHAR(60) NULL,
	CASE_SECON_DEALER_CODE_OF_DEAL  NVARCHAR(60) NULL,
	CASE_VEH_REG_PLATE				NVARCHAR(35) NULL,
	CASE_VEH_VIN_NUMBER				NVARCHAR(35) NULL,
	CASE_VEHMODEL_DERIVED_FROM_VIN  NVARCHAR(40) NULL,
	CR_OBJECT_ID					NVARCHAR(10) NULL,
	CRH_DEALER_ROA_CITY_TOWN		NVARCHAR(40) NULL,
	CRH_DEALER_ROA_COUNTRY			NVARCHAR(50) NULL,
	CRH_DEALER_ROA_HOUSE_NO			NVARCHAR(10) NULL,
	CRH_DEALER_ROA_ID				NVARCHAR(10) NULL,
	CRH_DEALER_ROA_NAME_1			NVARCHAR(40) NULL,
	CRH_DEALER_ROA_NAME_2			NVARCHAR(40) NULL,
	CRH_DEALER_ROA_PO_BOX			NVARCHAR(10) NULL,
	CRH_DEALER_ROA_POSTCODE_ZIP     NVARCHAR(10) NULL,
	CRH_DEALER_ROA_PREFIX_1			NVARCHAR(40) NULL,
	CRH_DEALER_ROA_PREFIX_2			NVARCHAR(40) NULL,
	CRH_DEALER_ROA_REGION_STATE     NVARCHAR(20) NULL,
	CRH_DEALER_ROA_STREET			NVARCHAR(60) NULL,
	CRH_DEALER_ROA_SUPPLEMENT_1     NVARCHAR(40) NULL,
	CRH_DEALER_ROA_SUPPLEMENT_2     NVARCHAR(40) NULL,
	CRH_DEALER_ROA_SUPPLEMENT_3     NVARCHAR(40) NULL,
	CRH_END_DATE					NVARCHAR(10) NULL,
	CRH_START_DATE					NVARCHAR(10) NULL,
	DMS_ACTIVITY_DESC				NVARCHAR(40) NULL,
	DMS_DAYS_OPEN					NVARCHAR(5) NULL,
	DMS_EVENT_TYPE					NVARCHAR(15) NULL,
	DMS_LICENSE_PLATE_REGISTRATION  NVARCHAR(35) NULL,
	DMS_POTENTIAL_CHANGE_OF_OWNERS  NVARCHAR(5) NULL,
	DMS_REPAIR_ORDER_CLOSED_DATE    NVARCHAR(10) NULL,
	DMS_REPAIR_ORDER_NUMBER			NVARCHAR(20) NULL,
	DMS_REPAIR_ORDER_OPEN_DATE      NVARCHAR(10) NULL,
	DMS_SECON_DEALER_CODE			NVARCHAR(60) NULL,
	DMS_SERVICE_ADVISOR				NVARCHAR(30) NULL,
	DMS_SERVICE_ADVISOR_ID			NVARCHAR(15) NULL,
	DMS_TECHNICIAN_ID				NVARCHAR(15) NULL,			-- BUG 13313 - 09/11/2016
	DMS_TECHNICIAN					NVARCHAR(30) NULL,			-- BUG 13313 - 09/11/2016
	DMS_TOTAL_CUSTOMER_PRICE		DECIMAL(17) NULL,
	DMS_USER_STATUS					NVARCHAR(30) NULL,
	DMS_USER_STATUS_CODE			NVARCHAR(5) NULL,
	DMS_VIN							NVARCHAR(35) NULL,
	LEAD_BRAND_CODE					NVARCHAR(5) NULL,
	LEAD_EMP_RESPONSIBLE_DEAL_NAME  NVARCHAR(81) NULL,
	LEAD_ENQUIRY_TYPE_CODE			NVARCHAR(4) NULL,
	LEAD_FUEL_TYPE_CODE				NVARCHAR(8) NULL,
	LEAD_IN_MARKET_DATE				NVARCHAR(10) NULL,
	LEAD_LEAD_CATEGORY_CODE			NVARCHAR(4) NULL,
	LEAD_LEAD_STATUS_CODE			NVARCHAR(30) NULL,
	LEAD_LEAD_STATUS_REASON_CODE    NVARCHAR(10) NULL,
	LEAD_MODEL_OF_INTEREST_CODE     NVARCHAR(5) NULL,
	LEAD_MODEL_YEAR					NVARCHAR(4) NULL,
	LEAD_NEW_USED_INDICATOR			NVARCHAR(10) NULL,
	LEAD_ORIGIN_CODE				NVARCHAR(3) NULL,
	LEAD_PRE_LAUNCH_MODEL			NVARCHAR(1) NULL,
	LEAD_PREF_CONTACT_METHOD		NVARCHAR(5) NULL,
	LEAD_SECON_DEALER_CODE			NVARCHAR(60) NULL,
	LEAD_VEH_SALE_TYPE_CODE			NVARCHAR(10) NULL,
	OBJECT_ID						NVARCHAR(10) NULL,
	ROADSIDE_ACTIVE_STATUS_CODE     NVARCHAR(5) NULL,
	ROADSIDE_ACTIVITY_DESC			NVARCHAR(40) NULL,
	ROADSIDE_COUNTRY_ISO_CODE       NVARCHAR(3) NULL,
	ROADSIDE_CUSTOMER_SUMMARY_INC   NVARCHAR(MAX) NULL,
	ROADSIDE_DATA_SOURCE			NVARCHAR(60) NULL,
	ROADSIDE_DATE_CALL_ANSWERED     NVARCHAR(10) NULL,
	ROADSIDE_DATE_CALL_RECEIVED     NVARCHAR(10) NULL,
	ROADSIDE_DATE_JOB_COMPLETED     NVARCHAR(10) NULL,
	ROADSIDE_DATE_RESOURCE_ALL      NVARCHAR(10) NULL,
	ROADSIDE_DATE_RESOURCE_ARRIVED  NVARCHAR(10) NULL,
	ROADSIDE_DATE_SECON_RES_ALL     NVARCHAR(10) NULL,
	ROADSIDE_DATE_SECON_RES_ARR     NVARCHAR(10) NULL,
	ROADSIDE_DRIVER_EMAIL			NVARCHAR(241) NULL,
	ROADSIDE_DRIVER_FIRST_NAME      NVARCHAR(40) NULL,
	ROADSIDE_DRIVER_LAST_NAME       NVARCHAR(40) NULL,
	ROADSIDE_DRIVER_MOBILE			NVARCHAR(30) NULL,
	ROADSIDE_DRIVER_TITLE			NVARCHAR(30) NULL,
	ROADSIDE_INCIDENT_CATEGORY      NVARCHAR(60) NULL,
	ROADSIDE_INCIDENT_COUNTRY       NVARCHAR(3) NULL,
	ROADSIDE_INCIDENT_DATE			NVARCHAR(10) NULL,
	ROADSIDE_INCIDENT_ID			NVARCHAR(20) NULL,
	ROADSIDE_INCIDENT_SUMMARY       NVARCHAR(MAX) NULL,
	ROADSIDE_INCIDENT_TIME			NVARCHAR(20) NULL,
	ROADSIDE_LICENSE_PLATE_REG_NO   NVARCHAR(15) NULL,
	ROADSIDE_PROVIDER				NVARCHAR(60) NULL,
	ROADSIDE_REPAIRING_SEC_DEAL_CD  NVARCHAR(60) NULL,
	ROADSIDE_RESOLUTION_TIME		NVARCHAR(20) NULL,
	ROADSIDE_TIME_CALL_ANSWERED     NVARCHAR(20) NULL,
	ROADSIDE_TIME_CALL_RECEIVED     NVARCHAR(20) NULL,
	ROADSIDE_TIME_JOB_COMPLETED     NVARCHAR(20) NULL,
	ROADSIDE_TIME_RESOURCE_ALL      NVARCHAR(20) NULL,
	ROADSIDE_TIME_RESOURCE_ARRIVED  NVARCHAR(20) NULL,
	ROADSIDE_TIME_SECON_RES_ALL     NVARCHAR(20) NULL,
	ROADSIDE_TIME_SECON_RES_ARR     NVARCHAR(20) NULL,
	ROADSIDE_VIN					NVARCHAR(35) NULL,
	ROADSIDE_WAIT_TIME				NVARCHAR(20) NULL,
	VEH_BRAND						NVARCHAR(10) NULL,
	VEH_BUILD_DATE					NVARCHAR(10) NULL,
	VEH_CHASSIS_NUMBER				NVARCHAR(30) NULL,
	VEH_COMMON_ORDER_NUMBER			NVARCHAR(35) NULL,
	VEH_COUNTRY_EQUIPMENT_CODE      NVARCHAR(60) NULL,
	VEH_CREATING_DEALER				NVARCHAR(40) NULL,
	VEH_CURR_PLANNED_DELIVERY_DATE  NVARCHAR(10) NULL,
	VEH_CURRENT_PLANNED_BUILD_DATE  NVARCHAR(10) NULL,
	VEH_DEA_NAME_LAST_SELLING_DEAL  NVARCHAR(81) NULL,
	VEH_DEALER_NAME_OF_SELLING_DEA  NVARCHAR(81) NULL,
	VEH_DELIVERED_DATE				NVARCHAR(10) NULL,
	VEH_DERIVATIVE					NVARCHAR(60) NULL,
	VEH_DRIVER_FULL_NAME			NVARCHAR(81) NULL,
	VEH_ENGINE_SIZE					NVARCHAR(40) NULL,
	VEH_EXTERIOR_COLOUR_CODE		NVARCHAR(10) NULL,
	VEH_EXTERIOR_COLOUR_DESC		NVARCHAR(40) NULL,
	VEH_EXTERIOR_COLOUR_SUPPL_CODE  NVARCHAR(10) NULL,
	VEH_EXTERIOR_COLOUR_SUPPL_DESC  NVARCHAR(60) NULL,
	VEH_FEATURE_CODE				NVARCHAR(MAX) NULL,
	VEH_FINANCE_PROD				NVARCHAR(40) NULL,
	VEH_FIRST_RETAIL_SALE			NVARCHAR(10) NULL,			-- 15234 - Size increased to 10
	VEH_FUEL_TYPE_CODE				NVARCHAR(10) NULL,			-- Task 325 - Size increased to 10 to match XML
	VEH_MODEL						NVARCHAR(40) NULL,
	VEH_MODEL_DESC					NVARCHAR(60) NULL,
	VEH_MODEL_YEAR					NVARCHAR(4) NULL,
	VEH_NUM_OF_OWNERS_RELATIONSHIP  INT NULL,
	VEH_ORIGIN						NVARCHAR(30) NULL,
	VEH_OWNERSHIP_STATUS			NVARCHAR(15) NULL,
	VEH_OWNERSHIP_STATUS_CODE       NVARCHAR(5) NULL,
	VEH_PAYMENT_TYPE				NVARCHAR(30) NULL,
	VEH_PREDICTED_REPLACEMENT_DATE  NVARCHAR(10) NULL,
	VEH_REACQUIRED_INDICATOR		NVARCHAR(1) NULL,
	VEH_REGISTRAT_LICENC_PLATE_NUM  NVARCHAR(15) NULL,
	VEH_REGISTRATION_DATE			NVARCHAR(10) NULL,
	VEH_SALE_TYPE_DESC				NVARCHAR(40) NULL,
	VEH_VIN							NVARCHAR(35) NULL,
	VEH_VISTA_CONTRACT_NUMBER       NVARCHAR(30) NULL,
	VISTACONTRACT_COMM_TY_SALE_DS   NVARCHAR(40) NULL,
	VISTACONTRACT_HANDOVER_DATE     NVARCHAR(10) NULL,
	VISTACONTRACT_PREV_VEH_BRAND    NVARCHAR(20) NULL,
	VISTACONTRACT_PREV_VEH_MODEL    NVARCHAR(40) NULL,
	VISTACONTRACT_SALES_MAN_CD_DES  NVARCHAR(60) NULL,
	VISTACONTRACT_SALES_MAN_FULNAM  NVARCHAR(40) NULL,
	VISTACONTRACT_SALESMAN_CODE     NVARCHAR(60) NULL,
	VISTACONTRACT_SECON_DEALER_CD   NVARCHAR(60) NULL,
	VISTACONTRACT_TRADE_IN_MANUFAC  NVARCHAR(40) NULL,
	VISTACONTRACT_TRADE_IN_MODEL    NVARCHAR(40) NULL,
	VISTACONTRACT_ACTIVITY_CATEGRY	NVARCHAR(3) NULL,
	VISTACONTRACT_RETAIL_PRICE		DECIMAL(17) NULL,
	VEH_APPR_WARNTY_TYPE			NVARCHAR(100) NULL,
	VEH_APPR_WARNTY_TYPE_DESC       NVARCHAR(60) NULL,
	VISTACONTRACTNAPPRO_RETAIL_WAR  NVARCHAR(5) NULL,
	VISTACONTRACTNAPPRO_RETAIL_DES  NVARCHAR(100) NULL,
	VISTACONTRACT_EXT_WARR			NVARCHAR(5) NULL,
	VISTACONTRACT_EXT_WARR_DESC     NVARCHAR(40) NULL,
	ACCT_CONSENT_JAGUAR_FAX			NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_FAX     NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_CHAT		NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_CHAT    NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_SMS			NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_SMS     NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_SMEDIA      NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_SMEDIA  NVARCHAR(60) NULL,
	ACCT_CONSENT_OVER_CONT_SUP_JAG  NVARCHAR(60) NULL,
	ACCT_CONSENT_OVER_CONT_SUP_LR   NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_PTSMR       NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_PTSMR   NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_PTVSM       NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_PTVSM   NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_PTAM		NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_PTAM    NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_PTNAU       NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_PTNAU	NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_PEVENT      NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_PEVENT  NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_PND3P       NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_PND3P   NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_PTSDWD      NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_PTSDWD  NVARCHAR(60) NULL,
	ACCT_CONSENT_JAGUAR_PTPA		NVARCHAR(60) NULL,
	ACCT_CONSENT_LAND_ROVER_PTPA    NVARCHAR(60) NULL,
	RESPONSE_ID						NVARCHAR(12) NULL,
	VISTACONTRACT_COMMON_ORDER_NUM	NVARCHAR(35) NULL,
	DMS_OTHER_RELATED_SERVICES		NVARCHAR(MAX) NULL,			-- BUG 14122 - 2017-09-06
	VEH_SALE_TYPE_CODE				NVARCHAR(6) NULL,			-- BUG 14344 - 2017-10-30
	VISTACONTRACT_COMM_TY_SALE_CD	NVARCHAR(6) NULL,			-- BUG 14344 - 2017-10-30
	[ISOAlpha2LanguageCode]			VARCHAR(50) NULL,			-- BUG 14677 - 2018-04-26 (ADD DEFAULT LANGUAGE WHEN NECESSARY)
	LEAD_STATUS_REASON_LEV1_DESC	NVARCHAR(40) NULL,
	LEAD_STATUS_REASON_LEV1_COD		NVARCHAR(20) NULL,
	LEAD_STATUS_REASON_LEV2_DESC	NVARCHAR(50) NULL,
	LEAD_STATUS_REASON_LEV2_COD		NVARCHAR(20) NULL,
	LEAD_STATUS_REASON_LEV3_DESC	NVARCHAR(30) NULL,
	LEAD_STATUS_REASON_LEV3_COD		NVARCHAR(20) NULL,
	JAGDIGITALEVENTSEXP				NVARCHAR(3) NULL,
	JAGDIGITALINCONTROL				NVARCHAR(3) NULL,
	JAGDIGITALOWNERVEHCOMM			NVARCHAR(3) NULL,
	JAGDIGITALPARTNERSSPONSORS		NVARCHAR(3) NULL,
	JAGDIGITALPRODSERV				NVARCHAR(3) NULL,
	JAGDIGITALPROMOTIONSOFFERS		NVARCHAR(3) NULL,
	JAGDIGITALSURVEYSRESEARCH		NVARCHAR(3) NULL,
	JAGEMAILEVENTSEXP				NVARCHAR(3) NULL,
	JAGEMAILINCONTROL				NVARCHAR(3) NULL,
	JAGEMAILOWNERVEHCOMM			NVARCHAR(3) NULL,
	JAGEMAILPARTNERSSPONSORS		NVARCHAR(3) NULL,
	JAGEMAILPRODSERV				NVARCHAR(3) NULL,
	JAGEMAILPROMOTIONSOFFERS		NVARCHAR(3) NULL,
	JAGEMAILSURVEYSRESEARCH			NVARCHAR(3) NULL,
	JAGPHONEEVENTSEXP				NVARCHAR(3) NULL,
	JAGPHONEINCONTROL				NVARCHAR(3) NULL,
	JAGPHONEOWNERVEHCOMM			NVARCHAR(3) NULL,
	JAGPHONEPARTNERSSPONSORS		NVARCHAR(3) NULL,
	JAGPHONEPRODSERV				NVARCHAR(3) NULL,
	JAGPHONEPROMOTIONSOFFERS		NVARCHAR(3) NULL,
	JAGPHONESURVEYSRESEARCH			NVARCHAR(3) NULL,
	JAGPOSTEVENTSEXP				NVARCHAR(3) NULL,
	JAGPOSTINCONTROL				NVARCHAR(3) NULL,
	JAGPOSTOWNERVEHCOMM				NVARCHAR(3) NULL,
	JAGPOSTPARTNERSSPONSORS			NVARCHAR(3) NULL,
	JAGPOSTPRODSERV					NVARCHAR(3) NULL,
	JAGPOSTPROMOTIONSOFFERS			NVARCHAR(3) NULL,
	JAGPOSTSURVEYSRESEARCH			NVARCHAR(3) NULL,
	JAGSMSEVENTSEXP					NVARCHAR(3) NULL,
	JAGSMSINCONTROL					NVARCHAR(3) NULL,
	JAGSMSOWNERVEHCOMM				NVARCHAR(3) NULL,
	JAGSMSPARTNERSSPONSORS			NVARCHAR(3) NULL,
	JAGSMSPRODSERV					NVARCHAR(3) NULL,
	JAGSMSPROMOTIONSOFFERS			NVARCHAR(3) NULL,
	JAGSMSSURVEYSRESEARCH			NVARCHAR(3) NULL,
	LRDIGITALEVENTSEXP				NVARCHAR(3) NULL,
	LRDIGITALINCONTROL				NVARCHAR(3) NULL,
	LRDIGITALOWNERVEHCOMM			NVARCHAR(3) NULL,
	LRDIGITALPARTNERSSPONSORS		NVARCHAR(3) NULL,
	LRDIGITALPRODSERV				NVARCHAR(3) NULL,
	LRDIGITALPROMOTIONSOFFERS		NVARCHAR(3) NULL,
	LRDIGITALSURVEYSRESEARCH		NVARCHAR(3) NULL,
	LREMAILEVENTSEXP				NVARCHAR(3) NULL,
	LREMAILINCONTROL				NVARCHAR(3) NULL,
	LREMAILOWNERVEHCOMM				NVARCHAR(3) NULL,
	LREMAILPARTNERSSPONSORS			NVARCHAR(3) NULL,
	LREMAILPRODSERV					NVARCHAR(3) NULL,
	LREMAILPROMOTIONSOFFERS			NVARCHAR(3) NULL,
	LREMAILSURVEYSRESEARCH			NVARCHAR(3) NULL,
	LRPHONEEVENTSEXP				NVARCHAR(3) NULL,
	LRPHONEINCONTROL				NVARCHAR(3) NULL,
	LRPHONEOWNERVEHCOMM				NVARCHAR(3) NULL,
	LRPHONEPARTNERSSPONSORS			NVARCHAR(3) NULL,
	LRPHONEPRODSERV					NVARCHAR(3) NULL,
	LRPHONEPROMOTIONSOFFERS			NVARCHAR(3) NULL,
	LRPHONESURVEYSRESEARCH			NVARCHAR(3) NULL,
	LRPOSTEVENTSEXP					NVARCHAR(3) NULL,
	LRPOSTINCONTROL					NVARCHAR(3) NULL,
	LRPOSTOWNERVEHCOMM				NVARCHAR(3) NULL,
	LRPOSTPARTNERSSPONSORS			NVARCHAR(3) NULL,
	LRPOSTPRODSERV					NVARCHAR(3) NULL,
	LRPOSTPROMOTIONSOFFERS			NVARCHAR(3) NULL,
	LRPOSTSURVEYSRESEARCH		    NVARCHAR(3) NULL,
	LRSMSEVENTSEXP					NVARCHAR(3) NULL,
	LRSMSINCONTROL				    NVARCHAR(3) NULL,
	LRSMSOWNERVEHCOMM		        NVARCHAR(3) NULL,
	LRSMSPARTNERSSPONSORS			NVARCHAR(3) NULL,
	LRSMSPRODSERV					NVARCHAR(3) NULL,
	LRSMSPROMOTIONSOFFERS			NVARCHAR(3) NULL,
	LRSMSSURVEYSRESEARCH			NVARCHAR(3) NULL,
	ACCT_NAME_PREFIX_CODE			NVARCHAR(4) NULL,
	ACCT_NAME_PREFIX				NVARCHAR(40) NULL,
	DMS_REPAIR_ORDER_NUMBER_UNIQUE	NVARCHAR(35) NULL,		-- BUG 15234 - Bringing all staging tables in line
	VEH_FUEL_TYPE					NVARCHAR(40) NULL,		-- BUG 15234 - Pre-existing columns now being included in the CRM staging tables
	CNT_ABTNR						NVARCHAR(4) NULL,		-- BUG 15234 - Pre-existing columns now being included in the CRM staging tables
	CNT_ADDRESS						NVARCHAR(241) NULL,		-- BUG 15234 - Pre-existing columns now being included in the CRM staging tables
	CNT_DPRTMNT						NVARCHAR(40) NULL,		-- BUG 15234 - Pre-existing columns now being included in the CRM staging tables
	CNT_FIRST_NAME					NVARCHAR(40) NULL,		-- BUG 15234 - Pre-existing columns now being included in the CRM staging tables
	CNT_FNCTN						NVARCHAR(40) NULL,		-- BUG 15234 - Pre-existing columns now being included in the CRM staging tables
	CNT_LAST_NAME					NVARCHAR(40) NULL,		-- BUG 15234 - Pre-existing columns now being included in the CRM staging tables
	CNT_PAFKT						NVARCHAR(4) NULL,		-- BUG 15234 - Pre-existing columns now being included in the CRM staging tables
	CNT_RELTYP						NVARCHAR(6) NULL,		-- BUG 15234 - Pre-existing columns now being included in the CRM staging tables
	CNT_TEL_NUMBER					NVARCHAR(30) NULL,		-- BUG 15234 - Pre-existing columns now being included in the CRM staging tables
	CONTACT_PER_ID					NVARCHAR(10) NULL,		-- BUG 15234 - Pre-existing columns now being included in the CRM staging tables
	ACCT_NAME_CREATING_DEA			NVARCHAR(81) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_MOBILE_PHONE				NVARCHAR(30) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_ACADEMIC_TITLE				NVARCHAR(40) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_ACADEMIC_TITLE_CODE			NVARCHAR(4) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_NAME_PREFIX_CODE			NVARCHAR(4) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_NAME_PREFIX					NVARCHAR(40) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGDIGITALEVENTSEXP			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGDIGITALINCONTROL			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGDIGITALOWNERVEHCOMM		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGDIGITALPARTNERSSPONSORS 	NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGDIGITALPRODSERV			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGDIGITALPROMOTIONSOFFERS	NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGDIGITALSURVEYSRESEARCH	NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGEMAILEVENTSEXP			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGEMAILINCONTROL			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGEMAILOWNERVEHCOMM		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGEMAILPARTNERSSPONSORS	NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGEMAILPRODSERV			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGEMAILPROMOTIONSOFFERS	NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGEMAILSURVEYSRESEARCH		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPHONEEVENTSEXP			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPHONEINCONTROL			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPHONEOWNERVEHCOMM 		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPHONEPARTNERSSPONSORS	NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPHONEPRODSERV			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPHONEPROMOTIONSOFFERS	NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPHONESURVEYSRESEARCH		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPOSTEVENTSEXP			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPOSTINCONTROL			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPOSTOWNERVEHCOMM			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPOSTPARTNERSSPONSORS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPOSTPRODSERV				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPOSTPROMOTIONSOFFERS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGPOSTSURVEYSRESEARCH		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGSMSEVENTSEXP				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGSMSINCONTROL				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGSMSOWNERVEHCOMM			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGSMSPARTNERSSPONSORS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGSMSPRODSERV				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGSMSPROMOTIONSOFFERS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_JAGSMSSURVEYSRESEARCH		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRDIGITALEVENTSEXP			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRDIGITALINCONTROL			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRDIGITALOWNERVEHCOMM		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRDIGITALPARTNERSSPONSORS	NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRDIGITALPRODSERV			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRDIGITALPROMOTIONSOFFERS	NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRDIGITALSURVEYSRESEARCH	NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LREMAILEVENTSEXP			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LREMAILINCONTROL			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LREMAILOWNERVEHCOMM 		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LREMAILPARTNERSSPONSORS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LREMAILPRODSERV				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LREMAILPROMOTIONSOFFERS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LREMAILSURVEYSRESEARCH		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPHONEEVENTSEXP			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPHONEINCONTROL			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPHONEOWNERVEHCOMM			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPHONEPARTNERSSPONSORS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPHONEPRODSERV				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPHONEPROMOTIONSOFFERS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPHONESURVEYSRESEARCH		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPOSTEVENTSEXP				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPOSTINCONTROL				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPOSTOWNERVEHCOMM			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPOSTPARTNERSSPONSORS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPOSTPRODSERV				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPOSTPROMOTIONSOFFERS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRPOSTSURVEYSRESEARCH		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRSMSEVENTSEXP				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRSMSINCONTROL				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRSMSOWNERVEHCOMM			NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRSMSPARTNERSSPONSORS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRSMSPRODSERV				NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRSMSPROMOTIONSOFFERS		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_LRSMSSURVEYSRESEARCH		NVARCHAR(3) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_TITLE						NVARCHAR(30) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_TITLE_CODE					NVARCHAR(4) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_PREF_LANGUAGE				NVARCHAR(16) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_PREF_LANGUAGE_CODE			NVARCHAR(2) NULL,		-- BUG 15234 - New columns added to CRM
	CNT_NON_ACADEMIC_TITLE_CODE		NVARCHAR(4) NULL,		-- Added with SC00146 version 5.7 (see BUG 16755)
	CNT_NON_ACADEMIC_TITLE			NVARCHAR(80) NULL,		-- Added with SC00146 version 5.7 (see BUG 16755)
	CNT_PREF_LAST_NAME				NVARCHAR(50) NULL,		-- Added with SC00146 version 5.3 (see BUG 15234/16755)
	ACCT_PREF_LAST_NAME				NVARCHAR(50) NULL,		-- Added with SC00146 version 5.3 (see BUG 15234/16755)
	VISTACONTRACT_PREVIOUS_RET_USE	NVARCHAR(4) NULL		-- Added for Task 325

) ON [PRIMARY]